/*
 * File: app/view/echoSlabCutView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.EchoSlabCutView', {
    extend: 'Ext.Container',
    alias: 'widget.echoSlabCutView',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.field.Toggle'
    ],

    config: {
        id: 'echoSlabCutView',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titleLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size',
                                    'title_cls'
                                ],
                                html: '离线二切'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 80,
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer61',
                                margin: '0 0 0 10',
                                width: 75,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '<'
                                    },
                                    {
                                        xtype: 'container',
                                        html: '返回'
                                    }
                                ],
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                //     var root = component.up('#root');
                                                //     var menuView = root.down('#menuView');
                                                //     var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"right"});
                                                //     root.animateActiveItem(menuView,slide);
                                                var root = Ext.getCmp('rootView');
                                                root.pop();
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer67',
                                margin: '0 10 0 0',
                                minWidth: 70,
                                layout: {
                                    type: 'hbox',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            var me = component;//3991206913302
                                            component.element.on('tap',function() {

                                                Ext.Viewport.setMasked({
                                                    xtype: 'loadmask',
                                                    fullscreen:true,
                                                    message: '请稍候......'
                                                });

                                                var echoSlabCutView = component.up('#echoSlabCutView');
                                                var dataview = echoSlabCutView.down('#dataView');
                                                var store = dataview.getStore();

                                                var matId = echoSlabCutView.down("#matId").getValue();

                                                Ext.Ajax.request({
                                                    url:rootUrl+'/echo/echo-cut-result/appEchoSlabCut.action',
                                                    method:'POST',
                                                    params: {
                                                        'matId' : matId
                                                    },
                                                    success: function(conn, response, options, eOpts) {
                                                        var text = conn.responseText;
                                                        var obj = Ext.decode(text);
                                                        if (obj.success) {
                                                            if (Ext.os.is('Android')) {
                                                                notice(obj.meta.message,null,'结果','确定');
                                                            } else {
                                                                Ext.Msg.alert('结果',obj.meta.message,Ext.emptyFn);
                                                            }
                                                            var currentView = component.up('#echoSlabCutView');
                                                            // 查询子坯
                                                            store.setParams({
                                                                'parentNo' : matId
                                                            });
                                                            store.getProxy().setTimeout(8000);
                                                            store.load({
                                                                callback:function(records,operation,success) {
                                                                    if(success == false) {
                                                                        if (Ext.os.is('Android')) {
                                                                            notice('连接异常！',null,'错误','确定');
                                                                        } else {
                                                                            Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                                                                        }
                                                                    }
                                                                }
                                                            });

                                                            Ext.Viewport.setMasked(false);

                                                        } else {
                                                            if (Ext.os.is('Android')) {
                                                                notice(obj.meta.message,null,'错误','确定');
                                                            } else {
                                                                Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                                                            }
                                                            Ext.Viewport.setMasked(false);
                                                        }

                                                    },
                                                    failure: function(conn, response, options, eOpts) {
                                                        var text = conn.responseText;
                                                        var obj = Ext.decode(text);
                                                        if (Ext.os.is('Android')) {
                                                            notice(obj.meta.message,null,'错误','确定');
                                                        } else {
                                                            Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                                                        }
                                                        Ext.Viewport.setMasked(false);
                                                    }
                                                });

                                            });
                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        cls: 'button_normal',
                                        itemId: 'mycontainer109',
                                        margin: '10 0',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center',
                                            pack: 'center'
                                        },
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '二切执行'
                                            }
                                        ],
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    component.element.on('touchstart',function() {
                                                        component.setCls('button_press');
                                                    });
                                                    component.element.on('touchend',function() {
                                                        component.setCls('button_normal');
                                                    });
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '10% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '板坯号',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'matId',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            }
                        ]
                    },

                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '扫描垛位',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'scanPile',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            }
                        ]
                    },

                    {
                        xtype: 'container',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                cls: [
                                    'base_font_family',
                                    'menu_view_bg'
                                ],
                                height: 40,
                                itemId: 'upBtn',
                                ui: 'small',
                                width: 70,
                                text: '上↑'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'base_font_family',
                                    'menu_view_bg'
                                ],
                                height: 40,
                                itemId: 'downBtn',
                                margin: '0 5',
                                ui: 'small',
                                width: 70,
                                text: '下↓'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'base_font_family',
                                    'menu_view_bg'
                                ],
                                height: 40,
                                itemId: 'inboundMatsBtn',
                                margin: '0 5',
                                ui: 'small',
                                width: 110,
                                text: '入库'
                            }
                        ]
                    },

                    {
                        xtype: 'container',
                        width: '98%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                flex: 7,
                                cls: [
                                    'table_head',
                                    'base_font_family'
                                ],
                                html: '物料号'
                            },
                            {
                                xtype: 'container',
                                flex: 3,
                                cls: [
                                    'table_head',
                                    'base_font_family'
                                ],
                                html: '层'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        flex: 1,
                        itemId: 'dataView',
                        width: '98%',
                        itemTpl: [
                            '<div style=" width:70%; text-align:center;float:left; ">{matNo}</div>',
                            '<div style=" width:28%; text-align:center;float:left; ">{sid}</div>'
                        ],
                        store: 'echoSlabCutStore'
                    }
                ],
            }
        ],
        listeners: [
            {
                fn: 'onScanPileBlur',
                event: 'blur',
                delegate: '#matId'
            },
            {
                fn: 'onUpBtnTap',
                event: 'tap',
                delegate: '#upBtn'
            },
            {
                fn: 'onDownBtnTap',
                event: 'tap',
                delegate: '#downBtn'
            },
            {
                fn: 'onInboundMatsBtnTap',
                event: 'tap',
                delegate: '#inboundMatsBtn'
            },
            {
                fn: 'onTargetSelectInitialize',
                event: 'initialize'
            }
        ]
    },

    onScanPileBlur: function(textfield, e, eOpts) {
        var echoSlabCutView = textfield.up('#echoSlabCutView');
        var dataview = echoSlabCutView.down('#dataView');
        var store = dataview.getStore();

        var zoneId = textfield.getValue();
        var zoneId = Trim(zoneId);
        if (zoneId!==''&&zoneId!==null&&zoneId!==undefined) {
            store.setParams({
                'parentNo' : zoneId
            });
            store.getProxy().setTimeout(8000);
            store.load({
                callback:function(records,operation,success) {
                    if(success == false) {
                        if (Ext.os.is('Android')) {
                            notice('连接异常！',null,'错误','确定');
                        } else {
                            Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                        }
                    }
                }
            });
        }
    },

    onUpBtnTap : function (textfield, e, eOpts) {
        var echoSlabCutView = textfield.up('#echoSlabCutView');
        var dataview = echoSlabCutView.down('#dataView');
        var store = dataview.getStore();

        // 选中行
        var selectedData = dataview.getSelection()[0].data;
        // 全部数据
        var allData = store.data.items;
        for (var i=0; i<allData.length; i++) {
            if(i == 0) {
                continue;
            }
            if(selectedData.matNo==allData[i].data.matNo) {
                var beforeMatId = allData[i-1].data.matNo;
                // 与前一个物料交换信息
                store.getAt(i-1).set("matNo",selectedData.matNo);
                store.getAt(i).set("matNo",beforeMatId);
                dataview.select(allData[i-1], true);
                //提交修改
                break;

            }
        }

    },

    onDownBtnTap : function (textfield, e, eOpts) {
        var echoSlabCutView = textfield.up('#echoSlabCutView');
        var dataview = echoSlabCutView.down('#dataView');
        var store = dataview.getStore();

        // 选中行
        var selectedData = dataview.getSelection()[0].data;
        // 全部数据
        var allData = store.data.items;
        for (var i=0; i<allData.length; i++) {
            if(i == allData.length-1) {
                break;
            }
            if(selectedData.matNo==allData[i].data.matNo) {
                var afterMatId = allData[i+1].data.matNo;
                // 与前一个物料交换信息
                store.getAt(i+1).set("matNo",selectedData.matNo);
                store.getAt(i).set("matNo",afterMatId);
                dataview.select(allData[i+1], true);
                //提交修改
                break;

            }
        }

    },

    onInboundMatsBtnTap : function (textfield, e, eOpts) {
        var echoSlabCutView = textfield.up('#echoSlabCutView');
        var dataview = echoSlabCutView.down('#dataView');
        var store = dataview.getStore();

        var zoneId = echoSlabCutView.down("#scanPile").getValue();

        // 全部数据
        var allData = store.data.items;

        // 拼凑json
        var inboundMats = "";
        if(allData.length == 0) {
            if (Ext.os.is('Android')) {
                notice('没有子坯信息，请切割母坯后入库',null,'结果','确定');
            } else {
                Ext.Msg.alert('结果','没有子坯信息，请切割母坯后入库',Ext.emptyFn);
            }
        } else {
            // 入库按钮
            var me = this;
            var jsonList = [];
            for (var i = 0; i < allData.length; i++) {
                var jsonData = {};
                jsonData['matId'] = allData[i].data.matNo;
                jsonData['seq'] = allData[i].data.sid;
                jsonList.push(jsonData);
            }
            inboundMats = Ext.encode(jsonList);
        }

        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            fullscreen:true,
            message: '请稍候......'
        });

        Ext.Ajax.request({
            url:rootUrl+'/wtm/wtm-location/appSlabCutIn.action',
            method:'POST',
            params: {
                'inboundMats' : inboundMats,
                'zoneId' : zoneId
            },
            success: function(conn, response, options, eOpts) {
                var text = conn.responseText;
                var obj = Ext.decode(text);
                if (obj.success) {
                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,null,'结果','确定');
                    } else {
                        Ext.Msg.alert('结果',obj.meta.message,Ext.emptyFn);
                    }
                } else {
                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,null,'错误','确定');
                    } else {
                        Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                    }
                }
                Ext.Viewport.setMasked(false);

            },
            failure: function(conn, response, options, eOpts) {
                var text = conn.responseText;
                var obj = Ext.decode(text);
                if (Ext.os.is('Android')) {
                    notice(obj.meta.message,null,'错误','确定');
                } else {
                    Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                }

                Ext.Viewport.setMasked(false);
            }
        });

    },

    onTargetSelectInitialize : function (component, eOpts) {
        var dataview = component.down('#dataView');
        var store = dataview.getStore();
        store.setParams({
            'parentNo' : 'xxx'
        });
        store.load();
    }

});