/*
 * File: app/view/PLTCMPutawayView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.PLTCMPutawayView', {
    extend: 'Ext.Container',
    alias: 'widget.pltcmPutawayView',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.field.Select'
    ],

    config: {
        id: 'pltcmPutawayView',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titleLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size',
                                    'title_cls'
                                ],
                                html: '酸轧下线'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 80,
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer1',
                                margin: '0 0 0 10',
                                minWidth: 70,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                var root = Ext.getCmp('rootView');
                                                root.pop();
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '<'
                                            },
                                            {
                                                xtype: 'container',
                                                html: '返回'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer67',
                                margin: '0 10 0 0',
                                minWidth: 70,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            var me = component;//3991206913302
                                            component.element.on('tap',function() {
                                                var view = component.up('#pltcmPutawayView');
                                                var data = view.getData();
                                                var target = view.down('#target');//.getValue();

                                                if (data===null||data===undefined||
                                                data.a===null||data.a===undefined||data.a==='') {
                                                    if (Ext.os.is('Android')) {
                                                        // window.plugins.toast.show('钢卷信息不能为空！', 'long', 'center',
                                                        // function(a){console.log('toast success: ' + a);},
                                                        // function(b){console.log('toast error: ' + b);});
                                                        notice('钢卷信息不能为空！',null,'错误','确定');
                                                    } else {
                                                        Ext.Msg.alert('错误','钢卷信息不能为空！',Ext.emptyFn);
                                                    }

                                                } else if (target.valueField===null||target.valueField===undefined||target.valueField==='') {
                                                    if (Ext.os.is('Android')) {
                                                        // window.plugins.toast.show('目标垛位不能为空！', 'long', 'center',
                                                        // function(a){console.log('toast success: ' + a);},
                                                        // function(b){console.log('toast error: ' + b);});
                                                        notice('目标垛位不能为空！',null,'错误','确定');
                                                    } else {
                                                        Ext.Msg.alert('错误','目标垛位不能为空！',Ext.emptyFn);
                                                    }

                                                } else {
                                                    // 入库按钮
                                                    var me = this;
                                                    var coil = Ext.decode(data.a);

                                                    var matId = coil.data[0].matId; // 钢卷号
                                                    var slotId = view.down('#target').getValue(); // 垛位号

                                                    Ext.Viewport.setMasked({
                                                        xtype: 'loadmask',
                                                        fullscreen:true,
                                                        message: '请稍候......'
                                                    });

                                                    Ext.Ajax.request({
                                                        url:rootUrl+'/wtm/inventory/appStore.action',
                                                        method:'POST',
                                                        params: {
                                                            'matId' : matId,
                                                            'targetSlotId' : slotId.substr(0,slotId.length-2)
                                                        },
                                                        success: function(conn, response, options, eOpts) {
                                                            console.log('success');
                                                            var text = conn.responseText;
                                                            var obj = Ext.decode(text);
                                                            console.log('conn = '+conn.responseText);
                                                            console.log('obj = '+obj.success);
                                                            if (obj.success) {
                                                                if (Ext.os.is('Android')) {
                                                                    // window.plugins.toast.show(obj.meta.message, 'long', 'center',
                                                                    // function(a){console.log('toast success: ' + a);},
                                                                    // function(b){console.log('toast error: ' + b);});
                                                                    notice(obj.meta.message,null,'提示','确定');
                                                                } else {
                                                                    Ext.Msg.alert('结果',obj.meta.message,Ext.emptyFn);
                                                                }
                                                                var currentView = component.up('#pltcmPutawayView');
                                                                currentView.down('#matId').setValue('');
                                                                currentView.down('#weight').setValue('');
                                                                currentView.down('#standard').setValue('');
                                                                currentView.down('#type').setValue('');
                                                                currentView.down('#scanPile').setValue('');
                                                                currentView.down('#target').setValue('');
                                                            } else {
                                                                if (Ext.os.is('Android')) {
                                                                    // window.plugins.toast.show('提交失败！', 'long', 'center',
                                                                    // function(a){console.log('toast success: ' + a);},
                                                                    // function(b){console.log('toast error: ' + b);});
                                                                    notice('提交失败！',null,'提示','确定');
                                                                } else {
                                                                    Ext.Msg.alert('错误','提交失败！',Ext.emptyFn);
                                                                }

                                                            }
                                                            Ext.Viewport.setMasked(false);
                                                        },
                                                        failure: function(conn, response, options, eOpts) {
                                                            var text = conn.responseText;
                                                            var obj = Ext.decode(text);
                                                            if (Ext.os.is('Android')) {
                                                                notice(obj.meta.message,null,'提示','确定');
                                                            } else {
                                                                Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                                                            }
                                                            Ext.Viewport.setMasked(false);
                                                        }
                                                    });
                                                }

                                            });
                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '入库'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '10% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '钢卷号',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'matId',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton4',
                                text: '扫码'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '重量',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'weight',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '规格',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'standard',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '钢种',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'type',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '步计量',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                baseCls: 'blue_border',
                                cls: 'margin_content',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'WAREHOUSE_HALLSelectField',
                                        inputCls: 'small_select_input',
                                        options: [
                                            {
                                                text: '1',
                                                value: '1'
                                            },
                                            {
                                                text: '2',
                                                value: '2'
                                            },
                                            {
                                                text: '3',
                                                value: '3'
                                            },
                                            {
                                                text: '4',
                                                value: '4'
                                            },
                                            {
                                                text: '5',
                                                value: '5'
                                            },
                                            {
                                                text: '6',
                                                value: '6'
                                            },
                                            {
                                                text: '7',
                                                value: '7'
                                            },
                                            {
                                                text: '8',
                                                value: '8'
                                            },
                                            {
                                                text: '9',
                                                value: '9'
                                            },
                                            {
                                                text: '10',
                                                value: '10'
                                            }
                                        ],
                                        usePicker: 'auto'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '扫描垛位',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'scanPile',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton4',
                                text: '扫码'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '垛位号',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        valueField: '',
                                        layer: '',
                                        cls: 'small_textfield_cls',
                                        itemId: 'target',
                                        clearIcon: false,
                                        inputCls: 'white_select_input',
                                        readOnly: false
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: false,
                                itemId: 'mybutton10',
                                text: '手动'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton11',
                                text: '扫码'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMytextfield1Blur',
                event: 'blur',
                delegate: '#matId'
            },
            {
                fn: 'onMatIdClearicontap',
                event: 'clearicontap',
                delegate: '#matId'
            },
            {
                fn: 'onMybutton4Tap',
                event: 'tap',
                delegate: '#mybutton4'
            },
            {
                fn: 'onWAREHOUSE_HALLSelectFieldChange1',
                event: 'change',
                delegate: '#WAREHOUSE_HALLSelectField'
            },
            {
                fn: 'onMytextfield1Blur11',
                event: 'blur',
                delegate: '#scanPile'
            },
            {
                fn: 'onMatIdClearicontap11',
                event: 'clearicontap',
                delegate: '#scanPile'
            },
            {
                fn: 'onMybutton4Tap11',
                event: 'tap',
                delegate: '#mybutton4'
            },
            {
                fn: 'onTargetFocus',
                event: 'focus',
                delegate: '#target'
            },
            {
                fn: 'onMybutton8Tap11',
                event: 'tap',
                delegate: '#mybutton10'
            },
            {
                fn: 'onMybutton11Tap',
                event: 'tap',
                delegate: '#mybutton11'
            },
            {
                fn: 'onPutawayViewHide',
                event: 'hide'
            }
        ]
    },

    onMytextfield1Blur: function(textfield, e, eOpts) {
        var currentView = textfield.up('#pltcmPutawayView');
        var myMatId = textfield.getValue();
        console.log('失去焦点:',myMatId);//5191400884600//3991006289100
        if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
            Ext.Ajax.request({
                url:rootUrl+'/mat/matmaterial/findByParams.action',
                method:'POST',
                params: {
                    'qm.matId':textfield.getValue()
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    console.log('obj = ',obj);
                    if (obj.data.length===1) {

                        currentView.setData({
                            a:text
                        });
                        var mass = Number(obj.data[0].matMass);
                        currentView.down('#weight').setValue((mass/1000)+'t');
                        currentView.down('#standard').setValue(obj.data[0].matWidth+'mm x'+obj.data[0].matThickness+'mm');
                        currentView.down('#type').setValue(obj.data[0].steelgradeId);
                    } else {
                        if (Ext.os.is('Android')) {
                            // window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                            //                           function(a){console.log('toast success: ' + a);},
                            //                           function(b){console.log('toast error: ' + b);});
                            notice('没有匹配的结果！',null,'提示','确定');
                        } else {
                            Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                        }

                    }

                },
                failure: function(conn, response, options, eOpts) {
                    if (Ext.os.is('Android')) {
                        // window.plugins.toast.show('连接异常！', 'long', 'center',
                        //                           function(a){console.log('toast success: ' + a);},
                        //                           function(b){console.log('toast error: ' + b);});
                        notice('连接异常！',null,'提示','确定');
                    } else {
                        Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    }

                }
            });
        } else {
            if (Ext.os.is('Android')) {
                // window.plugins.toast.show('钢卷号不能为空！', 'long', 'center',
                //                           function(a){console.log('toast success: ' + a);},
                //                           function(b){console.log('toast error: ' + b);});
                notice('钢卷号不能为空！',null,'提示','确定');
            } else {
                Ext.Msg.alert('错误','钢卷号不能为空！',Ext.emptyFn);
            }

        }

    },

    onMatIdClearicontap: function(textfield, e, eOpts) {
        var currentView = textfield.up('#pltcmPutawayView');
        currentView.down('#weight').setValue('');
        currentView.down('#type').setValue('');
        currentView.down('#standard').setValue('');
        currentView.down('#target').setValue('');
    },

    onMybutton4Tap: function(button, e, eOpts) {
        var putawayView = button.up('#pltcmPutawayView');
        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var text = result.text;
                    var myMatId = result.text;
                    putawayView.down('#matId').setValue(myMatId);
                    //服务器查询结果
                    //显示结果
                    if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
                        Ext.Ajax.request({
                            //     url: 'system/login!login.action',
                            //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
                            url:rootUrl+'/wtm/inventory-mat!findByPage.action',
                            method:'POST',
                            params: {
                                //         username: userName,
                                //         password: passWord,
                                'qm.matId':myMatId
                            },
                            success: function(conn, response, options, eOpts) {
                                console.log('success');
                                var text = conn.responseText;
                                var obj = Ext.decode(text);
                                console.log('conn = ',conn.responseText);
                                console.log('obj = ',obj);
                                if (obj.results===1) {
                                    putawayView.down('#weight').setValue(obj.items[0].matWeight+'t');
                                    putawayView.down('#standard').setValue(obj.items[0].matWidth+
                                                                          'mm x'+obj.items[0].matThickness+'mm');
                                    putawayView.down('#type').setValue(obj.items[0].steelGrade);
                                } else {
                                    if (Ext.os.is('Android')) {
                                        // window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                                        //                           function(a){console.log('toast success: ' + a);},
                                        //                           function(b){console.log('toast error: ' + b);});
                                        notice('没有匹配的结果！',null,'提示','确定');
                                    } else {
                                        Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                                    }
                                }

                            },
                            failure: function(conn, response, options, eOpts) {
                                if (Ext.os.is('Android')) {
                                    // window.plugins.toast.show('连接异常！', 'long', 'center',
                                    //                           function(a){console.log('toast success: ' + a);},
                                    //                           function(b){console.log('toast error: ' + b);});
                                    notice('连接异常！',null,'提示','确定');
                                } else {
                                    Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                                }
                            }
                        });
                    } else {
                        if (Ext.os.is('Android')) {
                            // window.plugins.toast.show('钢卷号扫描失败！', 'long', 'center',
                            //                           function(a){console.log('toast success: ' + a);},
                            //                           function(b){console.log('toast error: ' + b);});
                            notice('钢卷号扫描失败！',null,'提示','确定');
                        } else {
                            Ext.Msg.alert('错误','钢卷号扫描失败！',Ext.emptyFn);
                        }

                    }
                },
                //扫描失败回调
                function (error) {
                    if (Ext.os.is('Android')) {
                        // window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                        //                           function(a){console.log('toast success: ' + a);},
                        //                           function(b){console.log('toast error: ' + b);});
                        notice('条形码扫描失败！',null,'提示','确定');
                    } else {
                        Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                    }

                }
            );
        }
    },

    onWAREHOUSE_HALLSelectFieldChange1: function(selectfield, newValue, oldValue, eOpts) {

    },

    onMytextfield1Blur11: function(textfield, e, eOpts) {
        var me = this;
        var currentView = textfield.up('#pltcmPutawayView');
        var myMatId = textfield.getValue();
        var actualHallId = textfield.getValue().substring(0,3);
        console.log('失去焦点:',myMatId);//5191400884600//3991006289100
        if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
            Ext.Ajax.request({
                url:rootUrl+'/wtm/wtm-slot-switch/findByParams.action',
                method:'POST',
                params: {
                    'qm.actualHallId': actualHallId
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    console.log('obj = ',obj);
                    if (obj.data.length===1) {
                        var hallId = obj.data[0].hallId;
                        var sysSlot = me.transSoltId(textfield.getValue(), hallId);
                        currentView.down('#target').setValue(sysSlot);
                        currentView.down('#target').valueField = sysSlot;
                    } else {
                        if (Ext.os.is('Android')) {
                            // window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                            //                           function(a){console.log('toast success: ' + a);},
                            //                           function(b){console.log('toast error: ' + b);});
                            notice('没有匹配的结果！',null,'提示','确定');
                        } else {
                            Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                        }

                    }

                },
                failure: function(conn, response, options, eOpts) {
                    if (Ext.os.is('Android')) {
                        // window.plugins.toast.show('连接异常！', 'long', 'center',
                        //                           function(a){console.log('toast success: ' + a);},
                        //                           function(b){console.log('toast error: ' + b);});
                        notice('连接异常！',null,'提示','确定');
                    } else {
                        Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    }

                }
            });
        } else {
            if (Ext.os.is('Android')) {
                // window.plugins.toast.show('垛位号不能为空！', 'long', 'center',
                //                           function(a){console.log('toast success: ' + a);},
                //                           function(b){console.log('toast error: ' + b);});
                notice('垛位号不能为空！',null,'提示','确定');
            } else {
                Ext.Msg.alert('错误','垛位号不能为空！',Ext.emptyFn);
            }

        }

    },

    /**
     * 转换扫描的垛位号
     */
    transSoltId : function (actualSlotId, hallId) {
        // LYDH07031  -->  ZH01-H-07-03-1
        // 最终结果：跨-区-位-行
        var result = '';
        if(hallId) {
            result += hallId;
            if(actualSlotId.substring(3,4)) {
                result += '-' + actualSlotId.substring(3,4);
            }
            if(actualSlotId.substring(4,6)) {
                result += '-' + actualSlotId.substring(4,6);
            }
            if(actualSlotId.substring(6,8)) {
                result += '-' + actualSlotId.substring(6,8);
            }
            if(actualSlotId.substring(8)) {
                result += '-' + actualSlotId.substring(8);
            }
        }
        return result;
    },

    onMatIdClearicontap11: function(textfield, e, eOpts) {
        var currentView = textfield.up('#pltcmPutawayView');
        currentView.down('#weight').setValue('');
        currentView.down('#type').setValue('');
        currentView.down('#standard').setValue('');
        currentView.down('#target').setValue('');
    },

    onMybutton4Tap11: function(button, e, eOpts) {
        var putawayView = button.up('#pltcmPutawayView');
        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var text = result.text;
                    //             Ext.Msg.alert('结果',"We got a barcode\n<br>" +
                    //                                   "Result: " + result.text + "\n<br>" +
                    //                                   "Format: " + result.format + "\n<br>" +
                    //                                   "Cancelled: " + result.cancelled+"<br>",Ext.emptyFn);
                    var myMatId = result.text;
                    putawayView.down('#matId').setValue(myMatId);
                    //服务器查询结果
                    //显示结果
                    if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
                        Ext.Ajax.request({
                            //     url: 'system/login!login.action',
                            //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
                            url:rootUrl+'/wtm/inventory-mat!findByPage.action',
                            method:'POST',
                            params: {
                                //         username: userName,
                                //         password: passWord,
                                'qm.matId':myMatId
                            },
                            success: function(conn, response, options, eOpts) {
                                console.log('success');
                                var text = conn.responseText;
                                var obj = Ext.decode(text);
                                console.log('conn = ',conn.responseText);
                                console.log('obj = ',obj);
                                if (obj.results===1) {
                                    putawayView.down('#weight').setValue(obj.items[0].matWeight+'t');
                                    putawayView.down('#standard').setValue(obj.items[0].matWidth+
                                                                          'mm x'+obj.items[0].matThickness+'mm');
                                    putawayView.down('#type').setValue(obj.items[0].steelGrade);
                                } else {
                                    if (Ext.os.is('Android')) {
                                        // window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                                        //                           function(a){console.log('toast success: ' + a);},
                                        //                           function(b){console.log('toast error: ' + b);});
                                        notice('没有匹配的结果！',null,'提示','确定');
                                    } else {
                                        Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                                    }
                                }

                            },
                            failure: function(conn, response, options, eOpts) {
                                if (Ext.os.is('Android')) {
                                    // window.plugins.toast.show('连接异常！', 'long', 'center',
                                    //                           function(a){console.log('toast success: ' + a);},
                                    //                           function(b){console.log('toast error: ' + b);});
                                    notice('连接异常！',null,'提示','确定');
                                } else {
                                    Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                                }
                            }
                        });
                    } else {
                        if (Ext.os.is('Android')) {
                            // window.plugins.toast.show('钢卷号扫描失败！', 'long', 'center',
                            //                           function(a){console.log('toast success: ' + a);},
                            //                           function(b){console.log('toast error: ' + b);});
                            notice('钢卷号扫描失败！',null,'提示','确定');
                        } else {
                            Ext.Msg.alert('错误','钢卷号扫描失败！',Ext.emptyFn);
                        }

                    }
                },
                //扫描失败回调
                function (error) {
                    if (Ext.os.is('Android')) {
                        // window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                        //                           function(a){console.log('toast success: ' + a);},
                        //                           function(b){console.log('toast error: ' + b);});
                        notice('条形码扫描失败！',null,'提示','确定');
                    } else {
                        Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                    }

                }
            );
        }
        // Ext.Ajax.request({
        // //     url: 'system/login!login.action',
        // //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
        //     url:'http://10.4.55.204:7001/mes-wtm-app0924/wtm/downline!findByPage.action',
        //     method:'POST',
        // //     params: {
        // //         username: userName,
        // //         password: passWord,
        // //         crewId:crewId
        // //         //pageCheckCode:pageCheckCode
        // //     },
        //     success: function(conn, response, options, eOpts) {
        //         var text = conn.responseText;
        //         var obj = Ext.decode(text);
        // //         console.log('conn = ',conn.responseText);
        //         console.log('obj = ',obj.items[0]);
        //         putawayView.down('#weight').setValue(obj.items[0].matWeight);
        //         putawayView.down('#standard').setValue(obj.items[0].createdDt);
        //         putawayView.down('#type').setValue(obj.items[0].matId);

        // //         if (obj.success) {
        // //             var menuView = root.down('#menuView');
        // //             var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"left"});
        // //             root.animateActiveItem(menuView,slide);
        // //         } else {
        // //             Ext.msg.alert('错误','用户名或密码错误！',Ext.emptyFn);
        // //         }

        //     },
        //     failure: function(conn, response, options, eOpts) {
        //         Ext.msg.alert('错误','连接异常！',Ext.emptyFn);
        //     }
        // });
    },

    onTargetFocus: function(textfield, e, eOpts) {
        // var targetSelectDialog = Ext.create('widget.targetSelectDialog',{
        //     callback:function(displayValue,realValue,layer){
        //         console.log('putawayView callback');
        //         textfield.setValue(displayValue+'-'+layer);
        //         textfield.valueField = realValue;
        //     }
        // });
        // console.log('focuse = ',targetSelectDialog);
        // Ext.Viewport.add(targetSelectDialog);
    },

    onMybutton8Tap11: function(button, e, eOpts) {
        var view = button.up('#pltcmPutawayView');
        var target = view.down('#target');
        var targetSelectDialog = Ext.getCmp('targetSelectDialog');
        if (targetSelectDialog) {
            //     console.log(targetSelectDialog);
            targetSelectDialog.setCallback(function(displayValue,realValue,layer){
                console.log('pltcmPutawayView callback');
                target.setValue(displayValue+'-'+layer);
                target.valueField = displayValue;
                target.layer = layer;
                target.targetSlotSid = realValue;
            });
            targetSelectDialog.show();
        } else {
            targetSelectDialog = Ext.create('widget.targetSelectDialog',{
                callback:function(displayValue,realValue,layer){
                    console.log('pltcmPutawayView callback');
                    target.setValue(displayValue+'-'+layer);
                    target.valueField = displayValue;
                    target.layer = layer;
                    target.targetSlotSid = realValue;
                }
            });
            console.log('focuse = ',targetSelectDialog);
            Ext.Viewport.add(targetSelectDialog);
        }
        var store = targetSelectDialog.down('#dataView').getStore();
        store.removeAll();
    },

    onMybutton11Tap: function(button, e, eOpts) {
        var putawayView = button.up('#pltcmPutawayView');

        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var text = result.text;
                    var target = result.text;
                    putawayView.down('#target').setValue(target);
                    //服务器查询结果
                    //显示结果
                },
                //扫描失败回调
                function (error) {
                    //             showContainer.setHtml("Scanning failed: " + error);
                    if (Ext.os.is('Android')) {
                        // window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                        //                           function(a){console.log('toast success: ' + a);},
                        //                           function(b){console.log('toast error: ' + b);});
                        notice('条形码扫描失败！',null,'提示','确定');
                    } else {
                        Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                    }
                }
            );
        }
    },

    onPutawayViewHide: function(component, eOpts) {
        // component.destory();
    }

});