/*
 * File: app/view/RealRight.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.RealRight', {
    extend: 'Ext.Container',
    alias: 'widget.realright',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.field.Text',
        'Ext.Button'
    ],

    config: {
        id: 'realRight',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titileLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size'
                                ],
                                html: '成品接收'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer61',
                                margin: '0 0 0 10',
                                width: 75,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '<'
                                    },
                                    {
                                        xtype: 'container',
                                        html: '返回'
                                    }
                                ],
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                //     var root = component.up('#root');
                                                //     var menuView = root.down('#menuView');
                                                //     var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"right"});
                                                //     root.animateActiveItem(menuView,slide);
                                                var root = Ext.getCmp('rootView');
                                                root.pop();
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer203',
                                margin: '0 10 0 0',
                                width: 75,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            var me = component;//5591400507332
                                            component.element.on('tap',function() {
                                                var view = me.up('#realRight');
                                                var data = view.getData();
                                                var target = view.down('#target').getValue();


                                                if (data===null||data===undefined||
                                                data.a===null||data.a===undefined||data.a==='') {
                                                    if (Ext.os.is('Android')) {
                                                        window.plugins.toast.show('钢卷信息不能为空！', 'long', 'center',
                                                        function(a){console.log('toast success: ' + a);},
                                                        function(b){console.log('toast error: ' + b);});
                                                    } else {
                                                        Ext.Msg.alert('错误','钢卷信息不能为空！',Ext.emptyFn);
                                                    }
                                                } else if (target===null||target===undefined||target==='') {
                                                    if (Ext.os.is('Android')) {
                                                        window.plugins.toast.show('目标垛位不能为空！', 'long', 'center',
                                                        function(a){console.log('toast success: ' + a);},
                                                        function(b){console.log('toast error: ' + b);});
                                                    } else {
                                                        Ext.Msg.alert('错误','目标垛位不能为空！',Ext.emptyFn);
                                                    }
                                                } else {
                                                    console.log(data.a);
                                                    var coil = Ext.decode(data.a);
                                                    //     console.log('coil = ' , coil);
                                                    //     console.log('username = ' , sessionStorage.username);
                                                    //     console.log('target = ' , view.down('#target').getValue());
                                                    var obj = {};
                                                    //     obj.checkDate= '123';
                                                    //     obj.slotSid= '123';
                                                    obj.slotId= coil.items[0].slotId;
                                                    obj.soId= coil.items[0].soId;
                                                    obj.l4SoldtoPartyId= coil.items[0].l4SoldtoPartyId;
                                                    obj.l4MatNo= coil.items[0].l4MatNo;
                                                    obj.l4BatchNo= coil.items[0].l4BatchNo;
                                                    obj.matId= coil.items[0].matId;
                                                    obj.steelGrade= coil.items[0].steelGrade;
                                                    obj.matWidth= coil.items[0].matWidth;
                                                    obj.matThickness= coil.items[0].matThickness;
                                                    obj.matWeight= coil.items[0].matWeight;
                                                    obj.packingMethod= coil.items[0].packingMethod;
                                                    obj.grade= coil.items[0].grade;

                                                    obj.status= coil.items[0].status;
                                                    obj.prtId= coil.items[0].prtId;
                                                    //         obj.billDate= coil.items[0].billDate;
                                                    //         obj.soThickness= coil.items[0].soThickness;
                                                    //         obj.productUse= coil.items[0].productUse;
                                                    //         obj.waitRemark= coil.items[0].waitRemark;
                                                    var str = Ext.encode(obj);
                                                    console.log(str);
                                                    /*
                                                    "slotId": "LT01-A-01-01",
                                                    "soId": "0000211640",
                                                    "soItem": "10",
                                                    "l4SoldtoPartyId": "\u51b7\u8f67\u865a\u62df\u7528\u6237",
                                                    "l4MatNo": "43000050",
                                                    "l4BatchNo": "L9066843",
                                                    "matId": "3990903160010",
                                                    "steelGrade": "SPCC-0",
                                                    "matWidth": 1127,
                                                    "matThickness": 1.2,
                                                    "matWeight": 22.72,
                                                    "packingMethod": "N",
                                                    "grade": "004",
                                                    "status": "\u6210\u54c1\u5df2\u91ca\u653e",
                                                    "prtId": "66",
                                                    "billDate": "",
                                                    "soThickness": 0,
                                                    "productUse": "",
                                                    "waitRemark": ""
                                                    */


                                                    Ext.Ajax.request({
                                                        //     url: 'system/login!login.action',
                                                        //     url:'http://192.168.0.112/mes-wtm-app/wtm/inventory-check!saveRecords.action',
                                                        url:rootUrl+'/wtm/product-receive!receiveMats.action',
                                                        method:'POST',
                                                        params: {
                                                            'jsonProductReceiveList':str
                                                        },
                                                        success: function(conn, response, options, eOpts) {
                                                            console.log('success');
                                                            var text = conn.responseText;
                                                            var obj = Ext.decode(text);
                                                            console.log('conn = ',conn.responseText);
                                                            console.log('obj = ',obj);
                                                            if (obj.success) {
                                                                if (Ext.os.is('Android')) {
                                                                    window.plugins.toast.show(obj.message, 'long', 'center',
                                                                    function(a){console.log('toast success: ' + a);},
                                                                    function(b){console.log('toast error: ' + b);});
                                                                } else {
                                                                    Ext.Msg.alert('结果',obj.message,Ext.emptyFn);
                                                                }
                                                            } else {
                                                                if (Ext.os.is('Android')) {
                                                                    window.plugins.toast.show('提交失败！', 'long', 'center',
                                                                    function(a){console.log('toast success: ' + a);},
                                                                    function(b){console.log('toast error: ' + b);});
                                                                } else {
                                                                    Ext.Msg.alert('错误','提交失败！',Ext.emptyFn);
                                                                }

                                                            }

                                                        },
                                                        failure: function(conn, response, options, eOpts) {
                                                            if (Ext.os.is('Android')) {
                                                                window.plugins.toast.show('连接异常！', 'long', 'center',
                                                                function(a){console.log('toast success: ' + a);},
                                                                function(b){console.log('toast error: ' + b);});
                                                            } else {
                                                                Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                                                            }
                                                        }
                                                    });
                                                }

                                            });
                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '接收'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '10% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '钢卷号',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'matId',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton4',
                                text: '扫码'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '重量',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'weight',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '规格',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'standard',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '钢种',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'type',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        hidden: true,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '交易单号',
                                width: 80
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'DealingTicket',
                                        clearIcon: false,
                                        inputCls: 'white_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '垛位号',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'target',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton16',
                                text: '扫码'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMytextfield1Blur',
                event: 'blur',
                delegate: '#matId'
            },
            {
                fn: 'onMatIdClearicontap',
                event: 'clearicontap',
                delegate: '#matId'
            },
            {
                fn: 'onMybutton4Tap',
                event: 'tap',
                delegate: '#mybutton4'
            },
            {
                fn: 'onTargetFocus',
                event: 'focus',
                delegate: '#target'
            },
            {
                fn: 'onMybutton16Tap',
                event: 'tap',
                delegate: '#mybutton16'
            }
        ]
    },

    onMytextfield1Blur: function(textfield, e, eOpts) {
        console.log('失去焦点');
        var currentView = textfield.up('#realRight');
        var myMatId = textfield.getValue();
        console.log('失去焦点:',myMatId);//5591400507332
        if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
            Ext.Ajax.request({
                //     url: 'system/login!login.action',
                //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
                url:rootUrl+'/wtm/product-receive!findByPage.action',
                method:'POST',
                params: {
                    //         username: userName,
                    //         password: passWord,
                    'qm.matId':textfield.getValue()
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');

                    var text = conn.responseText;

                    //保存钢卷信息
                    currentView.setData({
                        a:text
                    });

                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    console.log('obj = ',obj);
                    if (obj.results===1) {
                        currentView.down('#weight').setValue(obj.items[0].matWeight+'t');
                        currentView.down('#standard').setValue(obj.items[0].matWidth+
                                    'mm x'+obj.items[0].matThickness+'mm');
                        currentView.down('#type').setValue(obj.items[0].steelGrade);
                        currentView.down('#target').setValue(obj.items[0].slotId);
        //                 console.log('重量：'+obj.items[0].matWeight+'，规格：'+obj.items[0].matWidth+
        //                             'mm x'+obj.items[0].matThickness+'mm,钢种:'+obj.items[0].steelGrade);
                    } else {
                        if (Ext.os.is('Android')) {
                            window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                                                      function(a){console.log('toast success: ' + a);},
                                                      function(b){console.log('toast error: ' + b);});
                        } else {
                            Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                        }
                    }

                },
                failure: function(conn, response, options, eOpts) {
                    if (Ext.os.is('Android')) {
                        window.plugins.toast.show('连接异常！', 'long', 'center',
                                                  function(a){console.log('toast success: ' + a);},
                                                  function(b){console.log('toast error: ' + b);});
                    } else {
                        Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    }
                }
            });
        } else {
            if (Ext.os.is('Android')) {
                window.plugins.toast.show('钢卷号不能为空！', 'long', 'center',
                                          function(a){console.log('toast success: ' + a);},
                                          function(b){console.log('toast error: ' + b);});
            } else {
                Ext.Msg.alert('错误','钢卷号不能为空！',Ext.emptyFn);
            }
        }

    },

    onMatIdClearicontap: function(textfield, e, eOpts) {
        var currentView = textfield.up('#realRight');
        currentView.down('#weight').setValue('');
        currentView.down('#standard').setValue('');
        currentView.down('#type').setValue('');
        currentView.down('#target').setValue('');
    },

    onMybutton4Tap: function(button, e, eOpts) {
        var currentView = button.up('#realRight');

        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var myMatId = result.text;
                    currentView.down('#matId').setValue(myMatId);
                    //服务器查询结果
                    //显示结果
                    if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
                        Ext.Ajax.request({
                            //     url: 'system/login!login.action',
                            //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
                            url:rootUrl+'/wtm/inventory-mat!findByPage.action',
                            method:'POST',
                            params: {
                                //         username: userName,
                                //         password: passWord,
                                'qm.matId':myMatId
                            },
                            success: function(conn, response, options, eOpts) {
                                console.log('success');
                                var text = conn.responseText;
                                var obj = Ext.decode(text);
                                console.log('conn = ',conn.responseText);
                                console.log('obj = ',obj);
                                if (obj.results===1) {
                                    currentView.down('#weight').setValue(obj.items[0].matWeight+'t');
                                    currentView.down('#standard').setValue(obj.items[0].matWidth+
                                                                          'mm x'+obj.items[0].matThickness+'mm');
                                    currentView.down('#type').setValue(obj.items[0].steelGrade);
                                    currentView.down('#current').setValue(obj.items[0].slotId);

                                } else {
                                    if (Ext.os.is('Android')) {
                                        window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                                                                  function(a){console.log('toast success: ' + a);},
                                                                  function(b){console.log('toast error: ' + b);});
                                    } else {
                                        Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                                    }
                                }

                            },
                            failure: function(conn, response, options, eOpts) {
                                if (Ext.os.is('Android')) {
                                    window.plugins.toast.show('连接异常！', 'long', 'center',
                                                              function(a){console.log('toast success: ' + a);},
                                                              function(b){console.log('toast error: ' + b);});
                                } else {
                                    Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                                }
                            }
                        });
                    } else {
                        if (Ext.os.is('Android')) {
                            window.plugins.toast.show('钢卷号扫描失败！', 'long', 'center',
                                                      function(a){console.log('toast success: ' + a);},
                                                      function(b){console.log('toast error: ' + b);});
                        } else {
                            Ext.Msg.alert('错误','钢卷号扫描失败！',Ext.emptyFn);
                        }
                    }
                    //服务器查询结果
                    //显示结果
                },
                //扫描失败回调
                function (error) {
        //             showContainer.setHtml("Scanning failed: " + error);
                    if (Ext.os.is('Android')) {
                        window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                                                  function(a){console.log('toast success: ' + a);},
                                                  function(b){console.log('toast error: ' + b);});
                    } else {
                        Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                    }
                }
            );
        }
    },

    onTargetFocus: function(textfield, e, eOpts) {
        // var targetSelectDialog = Ext.create('widget.targetSelectDialog',{
        //     callback:function(displayValue,realValue,layer){
        //         console.log('putawayView callback');
        //         textfield.setValue(displayValue+'-'+layer);
        //         textfield.valueField = realValue;
        //     }
        // });
        // console.log('focuse = ',targetSelectDialog);
        // Ext.Viewport.add(targetSelectDialog);
    },

    onMybutton16Tap: function(button, e, eOpts) {
        var currentView = button.up('#realRight');

        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var text = result.text;
                    var target = result.text;
                    currentView.down('#target').setValue(target);
                    //服务器查询结果
                    //显示结果
                },
                //扫描失败回调
                function (error) {
                    //             showContainer.setHtml("Scanning failed: " + error);
                    if (Ext.os.is('Android')) {
                                window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                                                          function(a){console.log('toast success: ' + a);},
                                                          function(b){console.log('toast error: ' + b);});
                            } else {
                                Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                            }
                }
            );
        }
    }

});