/*
 * File: app/view/ServerSetting.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.ServerSetting', {
    extend: 'Ext.Container',
    alias: 'widget.serverSetting',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.field.Text',
        'Ext.Button'
    ],

    config: {
        id: 'serverSetting',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titleLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size',
                                    'title_cls'
                                ],
                                html: '服务器设置'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 80,
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer1',
                                margin: '0 0 0 10',
                                minWidth: 70,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                //     var root = component.up('#root');
                                                //     var menuView = root.down('#menuView');
                                                //     var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"right"});
                                                //     root.animateActiveItem(menuView,slide);
                                                var root = Ext.getCmp('rootView');
                                                root.pop();
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '<'
                                            },
                                            {
                                                xtype: 'container',
                                                html: '返回'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer67',
                                margin: '0 10 0 0',
                                minWidth: 70,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            var me = component;//3991206913302
                                            component.element.on('tap',function() {
                                                var url = me.up('#serverSetting').down('#url').getValue();
                                                var port = me.up('#serverSetting').down('#port').getValue();
                                                var serverName = me.up('#serverSetting').down('#serverName').getValue();
                                                var newUrl = 'http://'+url+':'+port+'/'+serverName;
                                                console.log('newUrl = '+newUrl);
                                                var strRegex = "^((https|http|ftp|rtsp|mms)?://)"+
                                                //ftp的user@
                                                "?(([0-9a-z_!~*'().&=+$%-]+: )?[0-9a-z_!~*'().&=+$%-]+@)?" +
                                                // IP形式的URL- 199.194.52.184
                                                "(([0-9]{1,3}\.){3}[0-9]{1,3}" +
                                                // 允许IP和DOMAIN（域名）
                                                "|"+
                                                // 域名- www.
                                                "([0-9a-z_!~*'()-]+\.)*" +
                                                // 二级域名
                                                "([0-9a-z][0-9a-z-]{0,61})?[0-9a-z]\."+
                                                // first level domain- .com or .museum
                                                "[a-z]{2,6})" +
                                                // 端口- :80
                                                "(:[0-9]{1,4})?"+
                                                // a slash isn't required if there is no file name
                                                "((/?)|"+
                                                "(/[0-9a-z_!~*'().;?:@&=+$,%#-]+)+/?)$";
                                                var re=new RegExp(strRegex);
                                                //re.test()
                                                //     re.test(str_url);
                                                if (re.test(newUrl)) {
                                                    //         localStorage.url = newUrl.getValue();
                                                    localStorage.url = url;
                                                    localStorage.port = port;
                                                    localStorage.serverName = serverName;
                                                    rootUrl = 'http://'+url+':'+port+'/'+serverName;
                                                    mainInit();

                                                    var root = Ext.getCmp('rootView');
                                                    root.pop();
                                                } else {
                                                    if (Ext.os.is('Android')) {
                                                        window.plugins.toast.show('服务器地址错误！', 'long', 'center',
                                                        function(a){console.log('toast success: ' + a);},
                                                        function(b){console.log('toast error: ' + b);});
                                                    } else {
                                                        Ext.Msg.alert('错误','服务器地址错误！',Ext.emptyFn);
                                                    }
                                                }


                                            });
                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '保存'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '10% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '服务器地址',
                                width: 80
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'url',
                                        inputCls: 'white_select_input',
                                        readOnly: false
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton4',
                                text: '扫码'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '端口号',
                                width: 80
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'port',
                                        inputCls: 'white_select_input',
                                        readOnly: false
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '服务器名称',
                                width: 80
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'serverName',
                                        inputCls: 'white_select_input',
                                        readOnly: false
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        cls: [
                            'menu_view_bg',
                            'base_font_family'
                        ],
                        height: 45,
                        itemId: 'mybutton49',
                        margin: '5 0',
                        width: '100%',
                        text: '扫描'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMytextfield1Blur',
                event: 'blur',
                delegate: '#url'
            },
            {
                fn: 'onMybutton4Tap',
                event: 'tap',
                delegate: '#mybutton4'
            },
            {
                fn: 'onMybutton49Tap',
                event: 'tap',
                delegate: '#mybutton49'
            },
            {
                fn: 'onPutawayViewHide',
                event: 'hide'
            },
            {
                fn: 'onServerSettingInitialize',
                event: 'initialize'
            }
        ]
    },

    onMytextfield1Blur: function(textfield, e, eOpts) {

    },

    onMybutton4Tap: function(button, e, eOpts) {
        var putawayView = button.up('#cutInboundView');
        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var text = result.text;
                    //             Ext.Msg.alert('结果',"We got a barcode\n<br>" +
                    //                                   "Result: " + result.text + "\n<br>" +
                    //                                   "Format: " + result.format + "\n<br>" +
                    //                                   "Cancelled: " + result.cancelled+"<br>",Ext.emptyFn);
                    var myMatId = result.text;
                    putawayView.down('#matId').setValue(myMatId);
                    //服务器查询结果
                    //显示结果
                    if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
                        Ext.Ajax.request({
                            //     url: 'system/login!login.action',
                            //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
                            url:rootUrl+'/wtm/inventory-mat!findByPage.action',
                            method:'POST',
                            params: {
                                //         username: userName,
                                //         password: passWord,
                                'qm.matId':myMatId
                            },
                            success: function(conn, response, options, eOpts) {
                                console.log('success');
                                var text = conn.responseText;
                                var obj = Ext.decode(text);
                                console.log('conn = ',conn.responseText);
                                console.log('obj = ',obj);
                                if (obj.results===1) {
                                    putawayView.down('#weight').setValue(obj.items[0].matWeight+'t');
                                    putawayView.down('#standard').setValue(obj.items[0].matWidth+
                                                                          'mm x'+obj.items[0].matThickness+'mm');
                                    putawayView.down('#type').setValue(obj.items[0].steelGrade);
                                } else {
                                    if (Ext.os.is('Android')) {
                                        window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                                                                  function(a){console.log('toast success: ' + a);},
                                                                  function(b){console.log('toast error: ' + b);});
                                    } else {
                                        Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                                    }
                                }

                            },
                            failure: function(conn, response, options, eOpts) {
                                if (Ext.os.is('Android')) {
                                    window.plugins.toast.show('连接异常！', 'long', 'center',
                                                              function(a){console.log('toast success: ' + a);},
                                                              function(b){console.log('toast error: ' + b);});
                                } else {
                                    Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                                }
                            }
                        });
                    } else {
                        if (Ext.os.is('Android')) {
                            window.plugins.toast.show('钢卷号扫描失败！', 'long', 'center',
                                                      function(a){console.log('toast success: ' + a);},
                                                      function(b){console.log('toast error: ' + b);});
                        } else {
                            Ext.Msg.alert('错误','钢卷号扫描失败！',Ext.emptyFn);
                        }

                    }
                },
                //扫描失败回调
                function (error) {
                    if (Ext.os.is('Android')) {
                        window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                                                  function(a){console.log('toast success: ' + a);},
                                                  function(b){console.log('toast error: ' + b);});
                    } else {
                        Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                    }

                }
            );
        }
        // Ext.Ajax.request({
        // //     url: 'system/login!login.action',
        // //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
        //     url:'http://10.4.55.204:7001/mes-wtm-app0924/wtm/downline!findByPage.action',
        //     method:'POST',
        // //     params: {
        // //         username: userName,
        // //         password: passWord,
        // //         crewId:crewId
        // //         //pageCheckCode:pageCheckCode
        // //     },
        //     success: function(conn, response, options, eOpts) {
        //         var text = conn.responseText;
        //         var obj = Ext.decode(text);
        // //         console.log('conn = ',conn.responseText);
        //         console.log('obj = ',obj.items[0]);
        //         putawayView.down('#weight').setValue(obj.items[0].matWeight);
        //         putawayView.down('#standard').setValue(obj.items[0].createdDt);
        //         putawayView.down('#type').setValue(obj.items[0].matId);

        // //         if (obj.success) {
        // //             var menuView = root.down('#menuView');
        // //             var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"left"});
        // //             root.animateActiveItem(menuView,slide);
        // //         } else {
        // //             Ext.msg.alert('错误','用户名或密码错误！',Ext.emptyFn);
        // //         }

        //     },
        //     failure: function(conn, response, options, eOpts) {
        //         Ext.msg.alert('错误','连接异常！',Ext.emptyFn);
        //     }
        // });
    },

    onMybutton49Tap: function(button, e, eOpts) {
        var currentView = button.up('#serverSetting');
        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var text = result.text;
                    //             Ext.Msg.alert('结果',"We got a barcode\n<br>" +
                    //                                   "Result: " + result.text + "\n<br>" +
                    //                                   "Format: " + result.format + "\n<br>" +
                    //                                   "Cancelled: " + result.cancelled+"<br>",Ext.emptyFn);
                    var obj = Ext.decode(text);
        //             console.log();
                    currentView.down('#url').setValue(obj.url);
                    currentView.down('#port').setValue(obj.port);
                    currentView.down('#serverName').setValue(obj.serverName);

                },
                //扫描失败回调
                function (error) {
                    if (Ext.os.is('Android')) {
                        window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                                                  function(a){console.log('toast success: ' + a);},
                                                  function(b){console.log('toast error: ' + b);});
                    } else {
                        Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                    }

                }
            );
        }

    },

    onPutawayViewHide: function(component, eOpts) {
        // component.destory();
    },

    onServerSettingInitialize: function(component, eOpts) {
        var url = localStorage.url;
        var port = localStorage.port;
        var serverName = localStorage.serverName;
        if (url===undefined ||
            url === null || url=== ''||
            port===undefined ||
            port === null || port=== ''||
            serverName===undefined ||
            serverName === null || serverName=== ''
           ) {
            localStorage.url = '192.168.0.109';
            localStorage.port = '8080';
            localStorage.serverName = 'mes-wtm-app';
            url = '192.168.0.109';
            port = '8080';
            serverName = 'mes-wtm-app';
        }
        component.down('#url').setValue(url);
        component.down('#port').setValue(port);
        component.down('#serverName').setValue(serverName);
    }

});