/*
 * File: app/view/SimpleStoreCheck.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.SimpleStoreCheck', {
    extend: 'Ext.Container',
    alias: 'widget.simpleStoreCheck',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.field.Text',
        'Ext.Button'
    ],

    config: {
        id: 'simpleStoreCheck',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titileLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size'
                                ],
                                html: '临时盘库'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer61',
                                margin: '0 0 0 10',
                                width: 75,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '<'
                                    },
                                    {
                                        xtype: 'container',
                                        html: '返回'
                                    }
                                ],
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                //     var root = component.up('#root');
                                                //     var menuView = root.down('#menuView');
                                                //     var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"right"});
                                                //     root.animateActiveItem(menuView,slide);
                                                var root = Ext.getCmp('rootView');
                                                root.pop();
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer341',
                                margin: '0 10 0 0',
                                width: 75,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            var me = component;//3991206913302
                                            component.element.on('tap',function() {
                                                var view = me.up('#simpleStoreCheck');
                                                //     var data = view.getData();
                                                var target = view.down('#target').getValue();
                                                var myMatId = view.down('#matId').getValue();
                                                var scanPile = view.down('#scanPile').getValue();


                                                if (myMatId===null||myMatId===undefined||myMatId==='') {
                                                    if (Ext.os.is('Android')) {
                                                        window.plugins.toast.show('钢卷号不能为空！', 'long', 'center',
                                                        function(a){console.log('toast success: ' + a);},
                                                        function(b){console.log('toast error: ' + b);});
                                                    } else {
                                                        Ext.Msg.alert('错误','钢卷号不能为空！',Ext.emptyFn);
                                                    }
                                                } else if (target===null||target===undefined||target==='') {
                                                    if (Ext.os.is('Android')) {
                                                        window.plugins.toast.show('垛位不能为空！', 'long', 'center',
                                                        function(a){console.log('toast success: ' + a);},
                                                        function(b){console.log('toast error: ' + b);});
                                                    } else {
                                                        Ext.Msg.alert('错误','垛位不能为空！',Ext.emptyFn);
                                                    }
                                                } else {
                                                    //         var coil = Ext.decode(data.a);
                                                    //     console.log('coil = ' , coil);
                                                    //     console.log('username = ' , sessionStorage.username);
                                                    //     console.log('target = ' , view.down('#target').getValue());
                                                    var obj = {};
                                                    //     obj.checkDate= '123';
                                                    //     obj.slotSid= '123';
                                                    //         obj.matId= coil.items[0].matId;
                                                    //         obj.layer= coil.items[0].layer;
                                                    //         obj.matGrade= coil.items[0].steelGrade;
                                                    //         obj.matThickness= coil.items[0].matThickness;
                                                    //         obj.matWidth= coil.items[0].matWidth;
                                                    //         //     obj.matAct= '123';
                                                    //         obj.l4BatchId= coil.items[0].l4BatchNo;
                                                    //         obj.l4MatId= coil.items[0].l4MatNo;
                                                    //         obj.soId= coil.items[0].soId;
                                                    //         obj.soItem= coil.items[0].soItem;
                                                    //         obj.slotId= coil.items[0].slotId;
                                                    //----------------------
                                                    var tempStr = view.down('#target').getValue();
                                                    var index = tempStr.lastIndexOf('-');
                                                    var mySlotId = tempStr.substring(0,index);
                                                    var myLayer = tempStr.substring(index+1,index+2);
                                                    console.log('mySlotId = ' + mySlotId + ',myLayer = ' + myLayer);

                                                    //         obj.actualSlotId= view.down('#target').getValue();
                                                    obj.matId=myMatId;
                                                    obj.actualSlotId= tempStr;
                                                    obj.slotId= scanPile;
                                                    var str = Ext.encode(obj);
                                                    //     console.log(str);


                                                    Ext.Ajax.request({
                                                        //     url: 'system/login!login.action',
                                                        //     url:'http://192.168.0.112/mes-wtm-app/wtm/inventory-check!saveRecords.action',
                                                        url:rootUrl+'/wtm/inventory-check!saveRecords.action',
                                                        method:'POST',
                                                        params: {
                                                            'jsonInventoryCheckList':str
                                                        },
                                                        success: function(conn, response, options, eOpts) {
                                                            console.log('success');
                                                            var text = conn.responseText;
                                                            var obj = Ext.decode(text);
                                                            console.log('conn = ',conn.responseText);
                                                            console.log('obj = ',obj);
                                                            if (obj.success) {
                                                                if (Ext.os.is('Android')) {
                                                                    window.plugins.toast.show(obj.message, 'long', 'center',
                                                                    function(a){console.log('toast success: ' + a);},
                                                                    function(b){console.log('toast error: ' + b);});
                                                                    view.down('#target').setValue('');
                                                                    view.down('#matId').setValue('');
                                                                    view.down('#scanPile').setValue('');

                                                                } else {
                                                                    Ext.Msg.alert('错误',obj.message,Ext.emptyFn);
                                                                }
                                                            } else {
                                                                if (Ext.os.is('Android')) {
                                                                    window.plugins.toast.show(obj.message, 'long', 'center',
                                                                    function(a){console.log('toast success: ' + a);},
                                                                    function(b){console.log('toast error: ' + b);});
                                                                } else {
                                                                    Ext.Msg.alert('错误',obj.message,Ext.emptyFn);
                                                                }
                                                                //                 Ext.Msg.alert('错误','提交失败！',Ext.emptyFn);
                                                            }

                                                        },
                                                        failure: function(conn, response, options, eOpts) {
                                                            if (Ext.os.is('Android')) {
                                                                window.plugins.toast.show('连接异常！', 'long', 'center',
                                                                function(a){console.log('toast success: ' + a);},
                                                                function(b){console.log('toast error: ' + b);});
                                                            } else {
                                                                Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                                                            }
                                                        }
                                                    });
                                                }

                                            });
                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '确认'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '10% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '钢卷号',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'matId',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '扫描垛位',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'scanPile',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton4',
                                text: '扫码'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '实际号',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'target',
                                        inputCls: 'white_select_input',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton8',
                                text: '扫码'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton9',
                                text: '手动'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMytextfield1Blur11',
                event: 'blur',
                delegate: '#scanPile'
            },
            {
                fn: 'onMatIdClearicontap11',
                event: 'clearicontap',
                delegate: '#scanPile'
            },
            {
                fn: 'onMybutton4Tap11',
                event: 'tap',
                delegate: '#mybutton4'
            },
            {
                fn: 'onTargetFocus',
                event: 'focus',
                delegate: '#target'
            },
            {
                fn: 'onMybutton8Tap',
                event: 'tap',
                delegate: '#mybutton8'
            },
            {
                fn: 'onMybutton8Tap1',
                event: 'tap',
                delegate: '#mybutton9'
            }
        ]
    },

    onMytextfield1Blur11: function(textfield, e, eOpts) {
        console.log('失去焦点');
        var currentView = textfield.up('#simpleStoreCheck');
        var myMatId = textfield.getValue();
        console.log('失去焦点:',myMatId);//5191400884600//3991006289100
        if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
            Ext.Ajax.request({
                //     url: 'system/login!login.action',
                //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
                url:rootUrl+'/wtm/view-slot-switch!findSlot.action',
                method:'POST',
                params: {
                    //         username: userName,
                    //         password: passWord,
                    'qm.actualSlot':textfield.getValue()
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    console.log('obj = ',obj);
                    if (obj.results===1) {

        //                 currentView.setData({
        //                     a:text
        //                 });

        //                 currentView.down('#weight').setValue(obj.items[0].matWeight+'t');
        //                 currentView.down('#standard').setValue(obj.items[0].matWidth+
        //                             'mm x'+obj.items[0].matThickness+'mm');
        //                 currentView.down('#type').setValue(obj.items[0].steelGrade);
        //                 currentView.down('#produceLine').setValue(obj.items[0].produceLine);
        //                 currentView.down('#isClosed').setValue(obj.items[0].isClosed);
                        currentView.down('#target').setValue(obj.items[0].sysSlot);
                        currentView.down('#target').valueField = obj.items[0].sysSlot;
        //                 console.log('重量：'+obj.items[0].matWeight+'，规格：'+obj.items[0].matWidth+
        //                             'mm x'+obj.items[0].matThickness+'mm,钢种:'+obj.items[0].steelGrade);
                    } else {
                        currentView.down('#target').setValue('');
                        if (Ext.os.is('Android')) {
                            window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                                                      function(a){console.log('toast success: ' + a);},
                                                      function(b){console.log('toast error: ' + b);});
                        } else {
        //                     Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                        }

                    }

                },
                failure: function(conn, response, options, eOpts) {
                    if (Ext.os.is('Android')) {
                        window.plugins.toast.show('连接异常！', 'long', 'center',
                                                  function(a){console.log('toast success: ' + a);},
                                                  function(b){console.log('toast error: ' + b);});
                    } else {
                        Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    }

                }
            });
        } else {
            if (Ext.os.is('Android')) {
                window.plugins.toast.show('垛位号不能为空！', 'long', 'center',
                                          function(a){console.log('toast success: ' + a);},
                                          function(b){console.log('toast error: ' + b);});
            } else {
                Ext.Msg.alert('错误','垛位号不能为空！',Ext.emptyFn);
            }

        }

    },

    onMatIdClearicontap11: function(textfield, e, eOpts) {

    },

    onMybutton4Tap11: function(button, e, eOpts) {
        var putawayView = button.up('#putawayView');
        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var text = result.text;
                    //             Ext.Msg.alert('结果',"We got a barcode\n<br>" +
                    //                                   "Result: " + result.text + "\n<br>" +
                    //                                   "Format: " + result.format + "\n<br>" +
                    //                                   "Cancelled: " + result.cancelled+"<br>",Ext.emptyFn);
                    var myMatId = result.text;
                    putawayView.down('#matId').setValue(myMatId);
                    //服务器查询结果
                    //显示结果
                    if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
                        Ext.Ajax.request({
                            //     url: 'system/login!login.action',
                            //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
                            url:rootUrl+'/wtm/inventory-mat!findByPage.action',
                            method:'POST',
                            params: {
                                //         username: userName,
                                //         password: passWord,
                                'qm.matId':myMatId
                            },
                            success: function(conn, response, options, eOpts) {
                                console.log('success');
                                var text = conn.responseText;
                                var obj = Ext.decode(text);
                                console.log('conn = ',conn.responseText);
                                console.log('obj = ',obj);
                                if (obj.results===1) {
                                    putawayView.down('#weight').setValue(obj.items[0].matWeight+'t');
                                    putawayView.down('#standard').setValue(obj.items[0].matWidth+
                                                                          'mm x'+obj.items[0].matThickness+'mm');
                                    putawayView.down('#type').setValue(obj.items[0].steelGrade);
                                } else {
                                    if (Ext.os.is('Android')) {
                                        window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
                                                                  function(a){console.log('toast success: ' + a);},
                                                                  function(b){console.log('toast error: ' + b);});
                                    } else {
                                        Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                                    }
                                }

                            },
                            failure: function(conn, response, options, eOpts) {
                                if (Ext.os.is('Android')) {
                                    window.plugins.toast.show('连接异常！', 'long', 'center',
                                                              function(a){console.log('toast success: ' + a);},
                                                              function(b){console.log('toast error: ' + b);});
                                } else {
                                    Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                                }
                            }
                        });
                    } else {
                        if (Ext.os.is('Android')) {
                            window.plugins.toast.show('钢卷号扫描失败！', 'long', 'center',
                                                      function(a){console.log('toast success: ' + a);},
                                                      function(b){console.log('toast error: ' + b);});
                        } else {
                            Ext.Msg.alert('错误','钢卷号扫描失败！',Ext.emptyFn);
                        }

                    }
                },
                //扫描失败回调
                function (error) {
                    if (Ext.os.is('Android')) {
                        window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                                                  function(a){console.log('toast success: ' + a);},
                                                  function(b){console.log('toast error: ' + b);});
                    } else {
                        Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                    }

                }
            );
        }
        // Ext.Ajax.request({
        // //     url: 'system/login!login.action',
        // //     url:'http://192.168.0.112/mes-wtm-app/system/login!login.action',
        //     url:'http://10.4.55.204:7001/mes-wtm-app0924/wtm/downline!findByPage.action',
        //     method:'POST',
        // //     params: {
        // //         username: userName,
        // //         password: passWord,
        // //         crewId:crewId
        // //         //pageCheckCode:pageCheckCode
        // //     },
        //     success: function(conn, response, options, eOpts) {
        //         var text = conn.responseText;
        //         var obj = Ext.decode(text);
        // //         console.log('conn = ',conn.responseText);
        //         console.log('obj = ',obj.items[0]);
        //         putawayView.down('#weight').setValue(obj.items[0].matWeight);
        //         putawayView.down('#standard').setValue(obj.items[0].createdDt);
        //         putawayView.down('#type').setValue(obj.items[0].matId);

        // //         if (obj.success) {
        // //             var menuView = root.down('#menuView');
        // //             var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"left"});
        // //             root.animateActiveItem(menuView,slide);
        // //         } else {
        // //             Ext.msg.alert('错误','用户名或密码错误！',Ext.emptyFn);
        // //         }

        //     },
        //     failure: function(conn, response, options, eOpts) {
        //         Ext.msg.alert('错误','连接异常！',Ext.emptyFn);
        //     }
        // });
    },

    onTargetFocus: function(textfield, e, eOpts) {
        // var targetSelectDialog = Ext.create('widget.targetSelectDialog',{
        //     callback:function(displayValue,realValue,layer){
        //         console.log('putawayView callback');
        //         textfield.setValue(displayValue+'-'+layer);
        //         textfield.valueField = realValue;
        //     }
        // });
        // console.log('focuse = ',targetSelectDialog);
        // Ext.Viewport.add(targetSelectDialog);
    },

    onMybutton8Tap: function(button, e, eOpts) {
        var storeCheck = button.up('#storeCheck');

        //扫描功能
        if (Ext.os.is.Android) {
            cordova.plugins.barcodeScanner.scan(
                //扫描成功回调
                function (result) {
                    //解析结果
                    var text = result.text;
                    var target = result.text;
                    storeCheck.down('#target').setValue(target);
                    //服务器查询结果
                    //显示结果
                },
                //扫描失败回调
                function (error) {
                    //             showContainer.setHtml("Scanning failed: " + error);
                    if (Ext.os.is('Android')) {
                        window.plugins.toast.show('条形码扫描失败！', 'long', 'center',
                                                  function(a){console.log('toast success: ' + a);},
                                                  function(b){console.log('toast error: ' + b);});
                    } else {
                        Ext.Msg.alert('错误','条形码扫描失败！',Ext.emptyFn);
                    }
                }
            );
        }
    },

    onMybutton8Tap1: function(button, e, eOpts) {
        var view = button.up('#storeCheck');
        var target = view.down('#target');
        var targetSelectDialog = Ext.create('widget.targetSelectDialog',{
            callback:function(displayValue,realValue,layer){
                console.log('putawayView callback');
                target.setValue(displayValue+'-'+layer);
                target.valueField = realValue;
            }
        });
        console.log('focuse = ',targetSelectDialog);
        Ext.Viewport.add(targetSelectDialog);
    }

});