/*
 * File: app/view/TargetChangeingView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.TargetChangeingView', {
    extend: 'Ext.Container',
    alias: 'widget.targetchangeingview',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.field.Text',
        'Ext.Button'
    ],

    config: {
        id: 'targetChangeingView',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titileLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size'
                                ],
                                html: '扫码倒垛'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer61',
                                margin: '0 0 0 10',
                                minWidth: 70,
                                layout: 'hbox',
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                //     var root = component.up('#root');
                                                //     var menuView = root.down('#menuView');
                                                //     var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"right"});
                                                //     root.animateActiveItem(menuView,slide);
                                                //     var root = Ext.getCmp('rootView');
                                                //     root.pop();

                                                var currentView = component.up('#targetChangeingView');
                                                currentView.down('#matId').setValue('');
                                                currentView.down('#current').setValue('');
                                                currentView.down('#target').setValue('');
                                                currentView.down('#scanPile').setValue('');
                                                setTimeout(function() {
                                                    currentView.down('#matId').focus( );
                                                },1000);
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        cls: 'button_normal',
                                        itemId: 'mycontainer110',
                                        margin: '10 0',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center',
                                            pack: 'center'
                                        },
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    component.element.on('touchstart',function() {
                                                        component.setCls('button_press');
                                                    });
                                                    component.element.on('touchend',function() {
                                                        component.setCls('button_normal');
                                                    });
                                                },
                                                event: 'initialize'
                                            }
                                        ],
                                        items: [
                                            {
                                                xtype: 'container'
                                            },
                                            {
                                                xtype: 'container',
                                                html: '清空'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer148',
                                margin: '0 10 0 0',
                                minWidth: 70,
                                layout: 'hbox',
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            var me = component;//1410358722010
                                            component.element.on('tap',function() {

                                                Ext.Viewport.setMasked({
                                                    xtype: 'loadmask',
                                                    fullscreen:true,
                                                    message: '请稍候......'
                                                });

                                                var view = component.up('#targetChangeingView');
                                                var data = view.getData();
                                                var target = view.down('#target');//.getValue();


                                                if (data===null||data===undefined||
                                                data.a===null||data.a===undefined||data.a==='') {
                                                    if (Ext.os.is('Android')) {
                                                        notice('钢卷号不能为空！',null,'错误','确定');
                                                    } else {
                                                        Ext.Msg.alert('错误','钢卷信息不能为空！',Ext.emptyFn);
                                                    }
                                                    Ext.Viewport.setMasked(false);
                                                } else if (target.getValue()===null||target.getValue()===undefined||target.getValue()==='') {
                                                    if (Ext.os.is('Android')) {
                                                        notice('目标垛位不能为空！',null,'错误','确定');
                                                    } else {
                                                        Ext.Msg.alert('错误','目标垛位不能为空！',Ext.emptyFn);
                                                    }
                                                    Ext.Viewport.setMasked(false);
                                                } else {
                                                    // 倒剁按钮
                                                    var me = this;
                                                    var coil = Ext.decode(data.a);

                                                    var matId = coil.data[0].matId; // 钢卷号
                                                    var slotId = view.down('#target').getValue(); // 垛位号
                                                    var param = {
                                                        'matId' : matId,
                                                        'targetSlotId' : slotId.substr(0,slotId.length-2)
                                                    };

                                                    Ext.Ajax.request({
                                                        url:rootUrl+'/wtm/inventory/appMove.action',
                                                        method:'POST',
                                                        params: param,
                                                        success: function(conn, response, options, eOpts) {
                                                            console.log('success');
                                                            var text = conn.responseText;
                                                            var obj = Ext.decode(text);
                                                            if (obj.success) {
                                                                if (Ext.os.is('Android')) {
                                                                    notice(obj.meta.message,null,'结果','确定');
                                                                } else {
                                                                    Ext.Msg.alert('结果',obj.meta.message,Ext.emptyFn);
                                                                }

                                                                var currentView = component.up('#targetChangeingView');
                                                                currentView.down('#matId').setValue('');
                                                                currentView.down('#current').setValue('');
                                                                currentView.down('#target').setValue('');
                                                                currentView.down('#scanPile').setValue('');

                                                            } else if('session失效,请重登录！'===obj.message) {
                                                                //session失效,请重登录！
                                                                console.log('session失效,请重登录！');
                                                                if (Ext.os.is('Android')) {
                                                                    //                         window.plugins.toast.show(obj.message, 'long', 'center',
                                                                    //                                                   function(a){console.log('toast success: ' + a);},
                                                                    //                                                   function(b){console.log('toast error: ' + b);});
                                                                    notice(obj.meta.message,InvalidFunc(),'错误','确定');
                                                                } else {
                                                                    Ext.Msg.alert('错误',obj.message,InvalidFunc());
                                                                }
                                                            } else {
                                                                if (Ext.os.is('Android')) {
                                                                    notice(obj.meta.message,null,'错误','确定');
                                                                } else {
                                                                    Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                                                                }

                                                            }
                                                            // 隐藏等待提示
                                                            Ext.Viewport.setMasked(false);
                                                        },
                                                        failure: function(conn, response, options, eOpts) {
                                                            var text = conn.responseText;
                                                            var obj = Ext.decode(text);
                                                            if (Ext.os.is('Android')) {
                                                                notice(obj.meta.message,null,'错误','确定');
                                                            } else {
                                                                Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                                                            }

                                                            Ext.Viewport.setMasked(false);
                                                        }
                                                    });
                                                }

                                            });
                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        cls: 'button_normal',
                                        itemId: 'mycontainer111',
                                        margin: '10 0',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center',
                                            pack: 'center'
                                        },
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    component.element.on('touchstart',function() {
                                                        component.setCls('button_press');
                                                    });
                                                    component.element.on('touchend',function() {
                                                        component.setCls('button_normal');
                                                    });
                                                },
                                                event: 'initialize'
                                            }
                                        ],
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '确认倒垛'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '10% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '钢卷号',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'matId',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                itemId: 'topButton',
                                text: '置顶'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '原垛位',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'current',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '扫描垛位',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'scanPile',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: false,
                                itemId: 'slotIdSearchMatId',
                                text: '查询'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '目标垛位',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        targetSlotSid: '',
                                        cls: 'small_textfield_cls',
                                        itemId: 'target',
                                        inputCls: 'white_select_input',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton12',
                                text: '手动'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: false,
                                itemId: 'mybutton3',
                                text: '00'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMytextfield1Blur',
                event: 'blur',
                delegate: '#matId'
            },
            {
                fn: 'onMatIdClearicontap',
                event: 'clearicontap',
                delegate: '#matId'
            },
            {
                fn: 'onMybutton4Tap',
                event: 'tap',
                delegate: '#mybutton4'
            },
            {
                fn: 'onMytextfield1Blur11',
                event: 'blur',
                delegate: '#scanPile'
            },
            {
                fn: 'onMatIdClearicontap11',
                event: 'clearicontap',
                delegate: '#scanPile'
            },
            {
                fn: 'onSlotIdSearchMatIdTap',
                event: 'tap',
                delegate: '#slotIdSearchMatId'
            },
            {
                fn: 'onTargetFocus',
                event: 'focus',
                delegate: '#target'
            },
            {
                fn: 'onMybutton8Tap111',
                event: 'tap',
                delegate: '#mybutton12'
            },
            {
                fn: 'onMybutton3Tap',
                event: 'tap',
                delegate: '#mybutton3'
            },
            {
                fn: 'onTopButtonTap',
                event: 'tap',
                delegate: '#topButton'
            },
            {
                fn: 'onTargetChangeingViewHide',
                event: 'hide'
            }
        ]
    },

    onMytextfield1Blur: function(textfield, e, eOpts) {
        console.log('失去焦点');
        var currentView = textfield.up('#targetChangeingView');
        var myMatId = textfield.getValue();
        var myMatId = Trim(myMatId);
        console.log('失去焦点:',myMatId);//1410358722010
        if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
            Ext.Ajax.request({
                url:rootUrl+'/wtm/inventory/findByParams.action',
                method:'POST',
                params: {
                    'qm.matId':textfield.getValue()
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    console.log('obj = ',obj);
                    if (obj.data.length===1) {

                        currentView.setData({
                            a:text
                        });

                        currentView.down('#current').setValue(obj.data[0].slotId + '-' + obj.data[0].layer);

                        currentView.down('#scanPile').focus( );
                    } else {
                        if (Ext.os.is('Android')) {
        //                     window.plugins.toast.show('没有匹配的结果！', 'long', 'center',
        //                                               function(a){console.log('toast success: ' + a);},
        //                                               function(b){console.log('toast error: ' + b);});
                            notice('没有匹配的钢卷！',null,'错误','确定');
                        } else {
                            Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                        }
                    }

                },
                failure: function(conn, response, options, eOpts) {
                    if (Ext.os.is('Android')) {
        //                 window.plugins.toast.show('连接异常！', 'long', 'center',
        //                                           function(a){console.log('toast success: ' + a);},
        //                                           function(b){console.log('toast error: ' + b);});
                        notice('连接异常！',null,'错误','确定');
                    } else {
                        Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    }
                }
            });
        } else if (myMatId!==''&&myMatId!==null&&myMatId!==undefined){
            if (Ext.os.is('Android')) {
                notice('不是有效的钢卷号！',null,'错误','确定');
            } else {
                Ext.Msg.alert('错误','不是有效的钢卷号！',Ext.emptyFn);
            }
        } else {
        //     if (Ext.os.is('Android')) {
        //         notice('钢卷号不能为空！',null,'错误','确定');
        //     } else {
        //         Ext.Msg.alert('错误','钢卷号不能为空！',Ext.emptyFn);
        //     }

            var currentView = textfield.up('#targetChangeingView');
            currentView.down('#current').setValue('');
            currentView.down('#target').setValue('');
        }
    },

    onMatIdClearicontap: function(textfield, e, eOpts) {
        var currentView = textfield.up('#targetChangeingView');
        currentView.down('#current').setValue('');
        currentView.down('#target').setValue('');
    },

    onMybutton4Tap: function(button, e, eOpts) {
        var currentView = button.up('#targetChangeingView');
        currentView.down('#matId').setValue('');
        currentView.down('#current').setValue('');
        currentView.down('#target').setValue('');
        currentView.down('#scanPile').setValue('');


    },

    /**
     * 置顶按钮
     * @param button
     * @param e
     * @param eOpts
     */
    onTopButtonTap : function(button, e, eOpts) {
        var currentView = button.up('#targetChangeingView');
        var matId = currentView.down('#matId').getValue();
        var slotId = currentView.down('#current').getValue();

        Ext.Ajax.request({
            url:rootUrl+'/wtm/inventory/appCoilmoveTop.action',
            method:'POST',
            params: {
                'matId' : matId,
                'slotId' : slotId.substr(0,slotId.length-2)
            },
            success: function(conn, response, options, eOpts) {
                console.log('success');
                var text = conn.responseText;
                var obj = Ext.decode(text);
                console.log('conn = ',conn.responseText);
                console.log('obj = ',obj);
                if (obj.success) {
                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,null,'结果','确定');
                    } else {
                        Ext.Msg.alert('结果',obj.meta.message,Ext.emptyFn);
                    }
                } else {
                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,null,'错误','确定');
                    } else {
                        Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                    }
                }
            },
            failure: function(conn, response, options, eOpts) {
                if (Ext.os.is('Android')) {
                    notice('连接异常！',null,'错误','确定');
                } else {
                    Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                }
            }
        });
    },

    onMytextfield1Blur11: function(textfield, e, eOpts) {
        var me = this;
        console.log('失去焦点');
        var currentView = textfield.up('#targetChangeingView');
        var myMatId = textfield.getValue();
        var actualHallId = textfield.getValue().substring(0,3);
        console.log('失去焦点:',myMatId);//5191400884600//3991006289100
        if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
            Ext.Ajax.request({
                url:rootUrl+'/wtm/wtm-slot-switch/findByParams.action',
                method:'POST',
                params: {
                    'qm.actualHallId':actualHallId
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    console.log('obj = ',obj);
                    if (obj.data.length===1) {
                        var hallId = obj.data[0].hallId;
                        var sysSlot = me.transSoltId(textfield.getValue(), hallId);
                        currentView.down('#target').setValue(sysSlot);
                        currentView.down('#target').valueField = sysSlot;
                    } else {
                        if (Ext.os.is('Android')) {
                            notice('没有匹配的垛位！',null,'错误','确定');
                        } else {
                            Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                        }

                    }

                },
                failure: function(conn, response, options, eOpts) {
                    if (Ext.os.is('Android')) {
                        notice('连接异常！',null,'错误','确定');
                    } else {
                        Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    }

                }
            });
        } else {

        }

    },

    /**
     * 转换扫描的垛位号
     */
    transSoltId : function (actualSlotId, hallId) {
        // LYDH07031  -->  ZH01-H-07-03-1
        // 最终结果：跨-区-位-行
        var result = '';
        if(hallId) {
            result += hallId;
            if(actualSlotId.substring(3,4)) {
                result += '-' + actualSlotId.substring(3,4);
            }
            if(actualSlotId.substring(4,6)) {
                result += '-' + actualSlotId.substring(4,6);
            }
            if(actualSlotId.substring(6,8)) {
                result += '-' + actualSlotId.substring(6,8);
            }
            if(actualSlotId.substring(8)) {
                result += '-' + actualSlotId.substring(8);
            }
        }
        return result;
    },

    onMatIdClearicontap11: function(textfield, e, eOpts) {
        var currentView = textfield.up('#targetChangeingView');
        // currentView.down('#standard').setValue('');
        currentView.down('#target').setValue('');
    },

    onSlotIdSearchMatIdTap: function(button, e, eOpts) {
        var currentView = button.up('#targetChangeingView');
        var tempStr = currentView.down('#target').getValue();
        var matId = currentView.down('#matId').getValue();
        var index = tempStr.lastIndexOf('-');
        if (tempStr!==''&&tempStr!==null&&tempStr!==undefined) {
            var tempStr = currentView.down('#target').getValue();
            var index = tempStr.lastIndexOf('-');
            Ext.Ajax.request({
                url:rootUrl+'/wtm/inventory/findByParams.action',
                method:'POST',
                params: {
                    'qm.slotId':tempStr.substr(0,tempStr.length-2)
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    console.log('obj = ',obj);
                    if (obj.data.length===1) {

                        currentView.setData({
                            a:text
                        });

                        if (Ext.os.is('Android')) {
                            notice(tempStr+'该库区有钢卷，请先将库区中钢卷移到虚拟垛位!',null,'提示','确定');
                        } else {
                            Ext.Msg.alert("提示",tempStr+'该库区有钢卷，请先将库区中钢卷移到虚拟垛位!');
                        }
                    } else {
                        if (Ext.os.is('Android')) {
                            notice(tempStr+'该库区没有钢卷',null,'错误','确定');
                        } else {
                            Ext.Msg.alert('错误',tempStr+'该库区没有钢卷',Ext.emptyFn);
                        }
                    }

                },
                failure: function(conn, response, options, eOpts) {
                    if (Ext.os.is('Android')) {
        //                 window.plugins.toast.show('连接异常！', 'long', 'center',
        //                                           function(a){console.log('toast success: ' + a);},
        //                                           function(b){console.log('toast error: ' + b);});
                        notice('连接异常！',null,'错误','确定');
                    } else {
                        Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    }
                }
            });
        }  else {

        }
    },

    onTargetFocus: function(textfield, e, eOpts) {
        var target = textfield;
        var targetSelectDialog = Ext.getCmp('targetSelectDialog');
        if (targetSelectDialog) {
        //     console.log(targetSelectDialog);
            targetSelectDialog.setCallback(function(displayValue,realValue,layer){
                    console.log('putawayView callback');
                    target.setValue(displayValue+'-'+layer);
                    target.valueField = displayValue;
                    target.layer = layer;
                    target.targetSlotSid = realValue;
                });
            targetSelectDialog.show();
        } else {
            targetSelectDialog = Ext.create('widget.targetSelectDialog',{
                callback:function(displayValue,realValue,layer){
                    console.log('putawayView callback');
                    target.setValue(displayValue+'-'+layer);
                    target.valueField = displayValue;
                    target.layer = layer;
                    target.targetSlotSid = realValue;
                }
            });
            console.log('focuse = ',targetSelectDialog);
            Ext.Viewport.add(targetSelectDialog);
        }
        var store = targetSelectDialog.down('#dataView').getStore();
        store.removeAll();
    },

    onMybutton8Tap111: function(button, e, eOpts) {

    },

    /**
     * 00按钮，将目标库位的物料倒剁到对应的虚拟库位
     * @param button
     * @param e
     * @param eOpts
     */
    onMybutton3Tap: function(button, e, eOpts) {
        var currentView = button.up('#targetChangeingView');
        var target = currentView.down('#target').getValue();

        if(!target) {
            if (Ext.os.is('Android')) {
                notice('目标垛位不允许为空！',null,'结果','确定');
            } else {
                Ext.Msg.alert('结果','目标垛位不允许为空！',Ext.emptyFn);
            }
            return false;
        }

        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            fullscreen:true,
            message: '请稍候......'
        });

        var param = {
            'toSlotId' : target.substr(0,target.length-2)
        };

        Ext.Ajax.request({
            url:rootUrl+'/wtm/inventory/appMoveXn.action',
            method:'POST',
            params: param,
            success: function(conn, response, options, eOpts) {
                console.log('success');
                var text = conn.responseText;
                var obj = Ext.decode(text);
                if (obj.success) {
                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,null,'结果','确定');
                    } else {
                        Ext.Msg.alert('结果',obj.meta.message,Ext.emptyFn);
                    }
                } else if('session失效,请重登录！'===obj.message) {
                    //session失效,请重登录！
                    console.log('session失效,请重登录！');
                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,InvalidFunc(),'错误','确定');
                    } else {
                        Ext.Msg.alert('错误',obj.message,InvalidFunc());
                    }
                } else {
                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,null,'错误','确定');
                    } else {
                        Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                    }

                }
                // 隐藏等待提示
                Ext.Viewport.setMasked(false);
            },
            failure: function(conn, response, options, eOpts) {
                var text = conn.responseText;
                var obj = Ext.decode(text);
                if (Ext.os.is('Android')) {
                    notice(obj.meta.message,null,'错误','确定');
                } else {
                    Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                }
                Ext.Viewport.setMasked(false);
            }
        });
    },

    onTargetChangeingViewHide: function(component, eOpts) {
        // component.destory();
    }

});