/*
 * File: app/view/UnplanFeedingItem.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.UnplanFeedingItem', {
    extend: 'Ext.dataview.component.DataItem',
    alias: 'widget.unplanFeedingItem',

    requires: [
        'Ext.Container',
        'Ext.Button'
    ],

    config: {
        layout: 'hbox',
        items: [
            {
                xtype: 'container',
                padding: '10 10',
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        cls: 'light_blue_border',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                flex: 1,
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '钢卷号：'
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'matId'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '库：'
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'WAREHOUSEName'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '钢种：'
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'steelGrade'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '规格：'
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'standard'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '重量：'
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'weight'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '垛位号：'
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'slotId'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        hidden: true,
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '库存状态：'
                                            },
                                            {
                                                xtype: 'container'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                height: 50,
                                itemId: 'doFeedingButton',
                                margin: '0 5',
                                width: 65,
                                text: '投料'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybutton8Tap',
                event: 'tap',
                delegate: '#doFeedingButton'
            }
        ]
    },

    onMybutton8Tap: function(button, e, eOpts) {
        var item = button.up('unplanFeedingItem');
        var currRecord = item.getRecord();
        // Ext.Viewport.setMasked({
        //     xtype: 'loadmask',
        //     fullscreen:true,
        //     message: '正在投料，请稍候......'
        // });

        var unplannedFeeding = button.up('unplannedFeeding');
        var productionLineSelectField = unplannedFeeding.down('#productionLineSelectField').getValue();
        console.log('productionLineSelectField = '+productionLineSelectField);


        var obj = {};
        obj.matId= currRecord.get('matId');
        obj.inventoryStatus= currRecord.get('inventoryStatus');
        obj.matWidth= currRecord.get('matWidth');
        obj.matThickness= currRecord.get('matThickness');
        obj.matWeight= currRecord.get('matWeight');
        obj.steelGrade= currRecord.get('steelGrade');
        obj.warehouseId= currRecord.get('warehouseId');
        obj.warehouseName = currRecord.get('warehouseName');
        obj.slotId= currRecord.get('slotId');
        obj.maxlayer= currRecord.get('maxlayer');
        obj.stateOut = currRecord.get('stateOut');
        obj.version = currRecord.get('version');
        obj.createdDt = currRecord.get('createdDt');
        obj.sid = currRecord.get('sid');

        // obj.produceLine= currRecord.get('produceLine');
        // obj.rsId= currRecord.get('rsId');
        // obj.zoneName= currRecord.get('zoneName');
        // obj.soWidth= currRecord.get('soWidth');
        // obj.soThickness= currRecord.get('soThickness');
        // obj.rzWidth= currRecord.get('rzWidth');
        // obj.rzThickness = currRecord.get('rzThickness');
        // obj.matMass = currRecord.get('matMass');
        // obj.stgId = currRecord.get('stgId');
        // obj.pos = currRecord.get('pos');





        /*
         "matId": "1510111112020",
         "inventoryStatus": "RAW_MAT_RECEIVED",
         "matWidth": 1480,
         "matThickness": 4,
         "matWeight": 27,
         "steelGrade": "M3A33",
         "warehouseId": "YL",
         "warehouseName": "\u539f\u6599\u5e93",
         "slotId": "YL01-C-03-08",
         "maxlayer": 2,
         "stateOut": "1",
         "version": 1,
         "createdDt": "2015-11-18T15: 03: 39",
         "sid": "Sgai.model.wtm.unplanFeed.UnplanFeedModel-68",
         "createdBy": "",
         "createdTimestamp": null,
         "updatedBy": "",
         "updatedDt": null,
         "updatedTimestamp": null
        **/



        var str = Ext.encode(obj);
        console.log(str);
        if (Ext.os.is('Android')) {
            Ext.Ajax.request({
                url:rootUrl+'/wtm/unplan-feed!saveFeed.action',
                method:'POST',
                timeout:5000,
                params: {
                    'detaillist': str,
                    'produceLine':productionLineSelectField
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    if (obj.success) {
                        //提交后的动作
                        var feedingDataView = button.up('#feedingDataView');
                        feedingDataView.getStore().load();
                    }
                    window.plugins.toast.show(obj.message, 'long', 'center',
                                              function(a){console.log('toast success: ' + a);},
                                              function(b){console.log('toast error: ' + b);});
                    Ext.Viewport.setMasked(false);

                },
                failure: function(conn, response, options, eOpts) {
                    window.plugins.toast.show('连接异常！', 'long', 'center',
                                              function(a){console.log('toast success: ' + a);},
                                              function(b){console.log('toast error: ' + b);});
                    Ext.Viewport.setMasked(false);

                }
            });
        } else {
            Ext.Ajax.request({
                url:rootUrl+'/wtm/unplan-feed!saveFeed.action',
                method:'POST',
                timeout:5000,
                params: {
                    'detaillist': str,
                    'produceLine':productionLineSelectField
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    if (obj.success) {
                        //提交后的动作
                        var feedingDataView = button.up('#feedingDataView');
                        feedingDataView.getStore().load();
                    }
                    Ext.Msg.alert('消息',obj.message,Ext.emptyFn);
                    Ext.Viewport.setMasked(false);

                },
                failure: function(conn, response, options, eOpts) {
                    Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    Ext.Viewport.setMasked(false);

                }
            });
        }

    },

    updateRecord: function(record) {
        // console.log('updaterecord');
        // console.log('updaterecord',record);
        var me = this;
        if (record===null) {

        } else {
            me.down('#WAREHOUSEName').setHtml(record.get('warehouseName'));
            me.down('#steelGrade').setHtml(record.get('steelGrade'));
            me.down('#standard').setHtml(record.get('matThickness')+' * '+record.get('matWidth'));
            me.down('#weight').setHtml(record.get('matWeight'));
            me.down('#matId').setHtml(record.get('matId'));
            me.down('#slotId').setHtml(record.get('slotId'));
            if ('MAT_FEEDING'===record.get('inventoryStatus')) {
                me.down('#doFeedingButton').disable();
                me.down('#doFeedingButton').setHtml('已投');
            } else {
                me.down('#doFeedingButton').enable();
                me.down('#doFeedingButton').setHtml('投料');
            }
        }

    }

});