/*
 * File: app/view/wtmPankuView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.WtmPankuView', {
    extend: 'Ext.Container',
    alias: 'widget.wtmPankuView',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.field.Toggle'
    ],

    config: {
        id: 'wtmPankuView',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titleLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size',
                                    'title_cls'
                                ],
                                html: '盘库'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 80,
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer61',
                                margin: '0 0 0 10',
                                width: 75,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '<'
                                    },
                                    {
                                        xtype: 'container',
                                        html: '返回'
                                    }
                                ],
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                //     var root = component.up('#root');
                                                //     var menuView = root.down('#menuView');
                                                //     var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"right"});
                                                //     root.animateActiveItem(menuView,slide);
                                                var root = Ext.getCmp('rootView');
                                                root.pop();
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer67',
                                margin: '0 10 0 0',
                                minWidth: 70,
                                layout: {
                                    type: 'hbox',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            var me = component;//3991206913302
                                            component.element.on('tap',function() {

                                                Ext.Viewport.setMasked({
                                                    xtype: 'loadmask',
                                                    fullscreen:true,
                                                    message: '请稍候......'
                                                });

                                                var wtmPankuView = component.up('#wtmPankuView');
                                                var dataview = wtmPankuView.down('#dataView');
                                                var store = dataview.getStore();

                                                // 全部数据
                                                var allData = store.data.items;

                                                if(allData.length == 0) {
                                                    if (Ext.os.is('Android')) {
                                                        notice('请调整盘库内容',null,'结果','确定');
                                                    } else {
                                                        Ext.Msg.alert('结果','请调整盘库内容',Ext.emptyFn);
                                                    }
                                                } else {
                                                    // 入库按钮
                                                    var me = this;
                                                    var jsonList = [];
                                                    for (var i=0; i<allData.length; i++) {
                                                        var jsonData = {};
                                                        jsonData['sid'] = allData[i].data.sid;
                                                        jsonData['locationId'] = allData[i].data.locationId;
                                                        jsonData['matId'] = allData[i].data.matId;
                                                        jsonData['layer'] = allData[i].data.layer;
                                                        jsonList.push(jsonData);
                                                    }
                                                    Ext.Ajax.request({
                                                        url:rootUrl+'/wtm/wtm-location/locationMove.action',
                                                        method:'POST',
                                                        params: {
                                                            'detaillist' : Ext.encode(jsonList),
                                                            'operationType' : '4'
                                                        },
                                                        success: function(conn, response, options, eOpts) {
                                                            console.log('success');
                                                            var text = conn.responseText;
                                                            var obj = Ext.decode(text);
                                                            console.log('conn = '+conn.responseText);
                                                            console.log('obj = '+obj.success);
                                                            if (obj.success) {
                                                                if (Ext.os.is('Android')) {
                                                                    notice(obj.meta.message,null,'结果','确定');
                                                                } else {
                                                                    Ext.Msg.alert('结果',obj.meta.message,Ext.emptyFn);
                                                                }
                                                                var currentView = component.up('#wtmPankuView');
                                                                currentView.down('#scanPile').setValue('');
                                                            } else {

                                                                if (Ext.os.is('Android')) {
                                                                    //                         window.plugins.toast.show(obj.message, 'long', 'center',
                                                                    //                                                   function(a){console.log('toast success: ' + a);},
                                                                    //                                                   function(b){console.log('toast error: ' + b);});
                                                                    notice(obj.meta.message,null,'错误','确定');
                                                                } else {
                                                                    Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                                                                }

                                                            }
                                                            Ext.Viewport.setMasked(false);

                                                        },
                                                        failure: function(conn, response, options, eOpts) {
                                                            var text = conn.responseText;
                                                            var obj = Ext.decode(text);
                                                            if (Ext.os.is('Android')) {
                                                                notice(obj.meta.message,null,'错误','确定');
                                                            } else {
                                                                Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                                                            }

                                                            Ext.Viewport.setMasked(false);
                                                        }
                                                    });
                                                }

                                            });
                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        cls: 'button_normal',
                                        itemId: 'mycontainer109',
                                        margin: '10 0',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center',
                                            pack: 'center'
                                        },
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '盘库确认'
                                            }
                                        ],
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    component.element.on('touchstart',function() {
                                                        component.setCls('button_press');
                                                    });
                                                    component.element.on('touchend',function() {
                                                        component.setCls('button_normal');
                                                    });
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '10% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '扫描垛位',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'scanPile',
                                        inputCls: 'white_select_input'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                hidden: true,
                                itemId: 'mybutton4',
                                text: '扫码'
                            }
                        ]
                    },

                    {
                        xtype: 'container',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                cls: [
                                    'base_font_family',
                                    'menu_view_bg'
                                ],
                                height: 40,
                                itemId: 'upBtn',
                                ui: 'small',
                                width: 70,
                                text: '上↑'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'base_font_family',
                                    'menu_view_bg'
                                ],
                                height: 40,
                                itemId: 'downBtn',
                                margin: '0 5',
                                ui: 'small',
                                width: 70,
                                text: '下↓'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'base_font_family',
                                    'menu_view_bg'
                                ],
                                height: 40,
                                itemId: 'xnDaoduoBtn',
                                margin: '0 5',
                                ui: 'small',
                                width: 110,
                                text: '移至虚拟垛位'
                            }
                        ]
                    },

                    {
                        xtype: 'container',
                        width: '90%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                flex: 7,
                                cls: [
                                    'table_head',
                                    'base_font_family'
                                ],
                                html: '物料号'
                            },
                            {
                                xtype: 'container',
                                flex: 3,
                                cls: [
                                    'table_head',
                                    'base_font_family'
                                ],
                                html: '层'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        flex: 1,
                        itemId: 'dataView',
                        width: '90%',
                        itemTpl: [
                            '<div style=" width:65%; text-align:center;float:left; ">{matId}</div>',
                            '<div style=" width:25%; text-align:center;float:left; ">{layer}</div>'
                        ],
                        store: 'wtmPankuStore'
                    }
                ],
            }
        ],
        listeners: [
            {
                fn: 'onScanPileBlur',
                event: 'blur',
                delegate: '#scanPile'
            },
            {
                fn: 'onUpBtnTap',
                event: 'tap',
                delegate: '#upBtn'
            },
            {
                fn: 'onDownBtnTap',
                event: 'tap',
                delegate: '#downBtn'
            },
            {
                fn: 'onXnDaoduoBtnTap',
                event: 'tap',
                delegate: '#xnDaoduoBtn'
            },
            {
                fn: 'onTargetSelectInitialize',
                event: 'initialize'
            }
        ]
    },

    onScanPileBlur: function(textfield, e, eOpts) {
        var wtmPankuView = textfield.up('#wtmPankuView');
        var dataview = wtmPankuView.down('#dataView');
        var store = dataview.getStore();

        var zoneId = textfield.getValue();
        var zoneId = Trim(zoneId);
        if (zoneId!==''&&zoneId!==null&&zoneId!==undefined) {
            store.setParams({
                'qm.locationId' : zoneId
            });
            store.load();
        }
    },

    onUpBtnTap : function (textfield, e, eOpts) {
        var wtmPankuView = textfield.up('#wtmPankuView');
        var dataview = wtmPankuView.down('#dataView');
        var store = dataview.getStore();

        // 选中行
        var selectedData = dataview.getSelection()[0].data;
        // 全部数据
        var allData = store.data.items;
        for (var i=0; i<allData.length; i++) {
            if(i == 0) {
                continue;
            }
            if(selectedData.matId==allData[i].data.matId) {
                var beforeSid = allData[i-1].data.sid;
                var beforeMatId = allData[i-1].data.matId;
                // 与前一个物料交换信息
                store.getAt(i-1).set("sid",selectedData.sid);
                store.getAt(i-1).set("matId",selectedData.matId);
                store.getAt(i).set("sid",beforeSid);
                store.getAt(i).set("matId",beforeMatId);
                dataview.select(allData[i-1], true);
                //提交修改
                break;

            }
        }

    },

    onDownBtnTap : function (textfield, e, eOpts) {
        var wtmPankuView = textfield.up('#wtmPankuView');
        var dataview = wtmPankuView.down('#dataView');
        var store = dataview.getStore();

        // 选中行
        var selectedData = dataview.getSelection()[0].data;
        // 全部数据
        var allData = store.data.items;
        for (var i=0; i<allData.length; i++) {
            if(i == allData.length-1) {
                break;
            }
            if(selectedData.matId==allData[i].data.matId) {
                var afterSid = allData[i+1].data.sid;
                var afterMatId = allData[i+1].data.matId;
                // 与前一个物料交换信息
                store.getAt(i+1).set("sid",selectedData.sid);
                store.getAt(i+1).set("matId",selectedData.matId);
                store.getAt(i).set("sid",afterSid);
                store.getAt(i).set("matId",afterMatId);
                dataview.select(allData[i+1], true);
                //提交修改
                break;

            }
        }

    },

    onXnDaoduoBtnTap : function (textfield, e, eOpts) {
        var wtmPankuView = textfield.up('#wtmPankuView');
        var dataview = wtmPankuView.down('#dataView');
        var store = dataview.getStore();

        // 选中行
        var selectedData = dataview.getSelection()[0].data;

        Ext.Ajax.request({
            url:rootUrl+'/wtm/wtm-location/matMove.action',
            method:'POST',
            params: {
                'fromSlotId':selectedData.locationId,
                'toSlotId':'0/03/999/999',
                'matNo':selectedData.matId,
                'operationType':'4'
            },
            success: function(conn, response, options, eOpts) {
                console.log('success');
                var text = conn.responseText;
                var obj = Ext.decode(text);
                console.log('conn = ',conn.responseText);
                console.log('obj = ',obj);
                if (obj.success) {
                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,null,'结果','确定');
                    } else {
                        Ext.Msg.alert('结果',obj.meta.message,Ext.emptyFn);
                    }
                } else {

                    if (Ext.os.is('Android')) {
                        notice(obj.meta.message,null,'错误','确定');
                    } else {
                        Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                    }

                }
                Ext.Viewport.setMasked(false);

            },
            failure: function(conn, response, options, eOpts) {
                var text = conn.responseText;
                var obj = Ext.decode(text);
                if (Ext.os.is('Android')) {
                    notice(obj.meta.message,null,'错误','确定');
                } else {
                    Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                }

                Ext.Viewport.setMasked(false);
            }
        });

    },

    onTargetSelectInitialize : function (component, eOpts) {
        var dataview = component.down('#dataView');
        var store = dataview.getStore();
        store.setParams({
            'qm.locationId' : 'xxx'
        });
        store.load();
    }

});