/*
 * File: app/view/XS00List.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.view.XS00List', {
    extend: 'Ext.dataview.List',
    alias: 'widget.xs00List',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        callback: 'function(){}',
        height: 150,
        width: 180,
        hideOnMaskTap: true,
        modal: true,
        disableSelection: true,
        data: [
            {
                string: 'ZT01-0-00-00-1'
            },
            {
                string: 'LT01-0-00-00-1'
            },
            {
                string: 'ZT03-0-00-00-1'
            },
            {
                string: 'DX01-0-00-00-1'
            },
            {
                string: 'DX02-0-00-00-1'
            }
        ],
        itemTpl: [
            '<div>{string}</div>'
        ],
        listeners: [
            {
                fn: 'onListItemTap',
                event: 'itemtap'
            }
        ]
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var callbackFun = dataview.getCallback();
        callbackFun(record.get('string'));
        dataview.destroy();
    }

});