/*
 * File: app/model/PlannedFeedingModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.model.PlannedFeedingModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'matId'
            },
            {
                name: 'inventoryStatus'
            },
            {
                name: 'produceLine'
            },
            {
                name: 'rsId'
            },
            {
                name: 'zoneName'
            },
            {
                name: 'slotId'
            },
            {
                name: 'matWidth'
            },
            {
                name: 'matThickness'
            },
            {
                name: 'soWidth'
            },
            {
                name: 'soThickness'
            },
            {
                name: 'rzWidth'
            },
            {
                name: 'rzThickness'
            },
            {
                name: 'matMass'
            },
            {
                name: 'stgId'
            },
            {
                name: 'pos'
            },
            {
                name: 'warehouseName'
            },
            {
                name: 'stateOut'
            },
            {
                name: 'version'
            },
            {
                name: 'createdDt'
            },
            {
                name: 'matWeight'
            },
            {
                name: 'steelGrade'
            },
            {
                name: 'warehouseId'
            }
        ]
    }
});