/*
 * File: app/model/TargetSelectModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SYSM.model.TargetSelectModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'slotSid',
                type: 'int'
            },
            {
                name: 'slotId',
                type: 'string'
            },
            {
                name: 'warehouseName',
                type: 'string'
            },
            {
                name: 'hallName',
                type: 'string'
            },
            {
                name: 'zoneName',
                type: 'string'
            },
            {
                name: 'rowNo',
                type: 'string'
            },
            {
                name: 'locationNo',
                type: 'string'
            },
            {
                name: 'layer',
                type: 'int'
            },
            {
                name: 'stateIn',
                type: 'string'
            },
            {
                name: 'stateOut',
                type: 'int'
            },
            {
                name: 'holdFlag',
                type: 'int'
            }
        ]
    }
});